2023-07-10 18:30:50,412 INFO    StreamThr :17174 [internal.py:wandb_internal():86] W&B internal server running at pid: 17174, started at: 2023-07-10 18:30:50.411864
2023-07-10 18:30:50,414 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: status
2023-07-10 18:30:50,416 INFO    WriterThread:17174 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_183050-04o6n0t3/run-04o6n0t3.wandb
2023-07-10 18:30:50,417 DEBUG   SenderThread:17174 [sender.py:send():369] send: header
2023-07-10 18:30:50,417 DEBUG   SenderThread:17174 [sender.py:send():369] send: run
2023-07-10 18:30:52,195 INFO    SenderThread:17174 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_183050-04o6n0t3/files
2023-07-10 18:30:52,195 INFO    SenderThread:17174 [sender.py:_start_run_threads():1100] run started: 04o6n0t3 with start time 1688985050.41101
2023-07-10 18:30:52,196 DEBUG   SenderThread:17174 [sender.py:send_request():396] send_request: summary_record
2023-07-10 18:30:52,196 INFO    SenderThread:17174 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 18:30:52,202 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 18:30:52,203 DEBUG   SenderThread:17174 [sender.py:send_request():396] send_request: check_version
2023-07-10 18:30:52,383 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 18:30:52,387 DEBUG   HandlerThread:17174 [system_info.py:__init__():31] System info init
2023-07-10 18:30:52,387 DEBUG   HandlerThread:17174 [system_info.py:__init__():46] System info init done
2023-07-10 18:30:52,387 INFO    HandlerThread:17174 [system_monitor.py:start():181] Starting system monitor
2023-07-10 18:30:52,388 INFO    HandlerThread:17174 [system_monitor.py:probe():201] Collecting system info
2023-07-10 18:30:52,388 INFO    SystemMonitor:17174 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 18:30:52,389 INFO    SystemMonitor:17174 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 18:30:52,390 INFO    SystemMonitor:17174 [interfaces.py:start():190] Started disk monitoring
2023-07-10 18:30:52,390 INFO    SystemMonitor:17174 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 18:30:52,392 INFO    SystemMonitor:17174 [interfaces.py:start():190] Started memory monitoring
2023-07-10 18:30:52,392 INFO    SystemMonitor:17174 [interfaces.py:start():190] Started network monitoring
2023-07-10 18:30:52,402 DEBUG   HandlerThread:17174 [system_info.py:probe():195] Probing system
2023-07-10 18:30:52,405 DEBUG   HandlerThread:17174 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 18:30:52,405 DEBUG   HandlerThread:17174 [system_info.py:probe():240] Probing system done
2023-07-10 18:30:52,405 DEBUG   HandlerThread:17174 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T10:30:52.402270', 'startedAt': '2023-07-10T10:30:50.403368', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3309.695916666667, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5099.151, 'min': 800.0, 'max': 5100.0}, {'current': 5100.075, 'min': 800.0, 'max': 5100.0}, {'current': 4884.149, 'min': 800.0, 'max': 5100.0}, {'current': 5096.59, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.06, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5099.505, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.01787567138671875}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-10 18:30:52,405 INFO    HandlerThread:17174 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 18:30:52,405 INFO    HandlerThread:17174 [system_monitor.py:probe():214] Publishing system info
2023-07-10 18:30:52,405 DEBUG   HandlerThread:17174 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 18:30:52,405 DEBUG   HandlerThread:17174 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 18:30:52,405 DEBUG   HandlerThread:17174 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 18:30:53,161 DEBUG   HandlerThread:17174 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 18:30:53,163 INFO    HandlerThread:17174 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 18:30:53,165 DEBUG   SenderThread:17174 [sender.py:send():369] send: files
2023-07-10 18:30:53,165 INFO    SenderThread:17174 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 18:30:53,171 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 18:30:53,171 DEBUG   SenderThread:17174 [sender.py:send_request():396] send_request: stop_status
2023-07-10 18:30:53,198 INFO    Thread-17 :17174 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_183050-04o6n0t3/files/wandb-metadata.json
2023-07-10 18:30:53,198 INFO    Thread-17 :17174 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_183050-04o6n0t3/files/requirements.txt
2023-07-10 18:30:53,198 INFO    Thread-17 :17174 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_183050-04o6n0t3/files/wandb-summary.json
2023-07-10 18:30:53,198 INFO    Thread-17 :17174 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_183050-04o6n0t3/files/conda-environment.yaml
2023-07-10 18:30:53,397 DEBUG   SenderThread:17174 [sender.py:send():369] send: telemetry
2023-07-10 18:30:53,996 ERROR   wandb-upload_0:17174 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/04o6n0t3/wandb-metadata.json?Expires=1689071453&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lZHcjGGd6%2FV0Pchqc%2FWc21zgLORH1Hfb%2BTW0LXVCp1lOzskqxjapuvVl7rAm0ghzcFjyWm4eXu%2BOewrWELeUCB1dCsD%2BAMBBP2C96ZYOnGisOZnpWD%2BofuuygRgxn4NuxoKRtWbOR8k2%2B5Trd4Tt7%2BMJqN%2FWSok945oWyR2%2Fm0COv44DRjqVdTicmdJH0%2B8iN%2F34DyT95zgP83QqHi%2F478UP6lA04gg%2Fa%2FSz0McUbgAjqZfhvEkJVJwj3bHsu380XN0UP1XUgUYOyP9mfDvhQP5hvQC5ADzGymgrTi3a%2BHllSZ%2BeioLJuQujixtL4%2F0MUlIOGanbg5S13sv7coLCaQ%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/04o6n0t3/wandb-metadata.json?Expires=1689071453&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lZHcjGGd6%2FV0Pchqc%2FWc21zgLORH1Hfb%2BTW0LXVCp1lOzskqxjapuvVl7rAm0ghzcFjyWm4eXu%2BOewrWELeUCB1dCsD%2BAMBBP2C96ZYOnGisOZnpWD%2BofuuygRgxn4NuxoKRtWbOR8k2%2B5Trd4Tt7%2BMJqN%2FWSok945oWyR2%2Fm0COv44DRjqVdTicmdJH0%2B8iN%2F34DyT95zgP83QqHi%2F478UP6lA04gg%2Fa%2FSz0McUbgAjqZfhvEkJVJwj3bHsu380XN0UP1XUgUYOyP9mfDvhQP5hvQC5ADzGymgrTi3a%2BHllSZ%2BeioLJuQujixtL4%2F0MUlIOGanbg5S13sv7coLCaQ%3D%3D
2023-07-10 18:30:53,996 ERROR   wandb-upload_0:17174 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3614'}
2023-07-10 18:30:53,996 ERROR   wandb-upload_0:17174 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/04o6n0t3/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 18:30:54,196 INFO    Thread-17 :17174 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_183050-04o6n0t3/files/output.log
2023-07-10 18:30:54,570 ERROR   wandb-upload_0:17174 [upload_job.py:push():136] Failed to upload file: /tmp/tmp1qnk896dwandb/tbonvbwu-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/04o6n0t3/wandb-metadata.json?Expires=1689071453&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lZHcjGGd6%2FV0Pchqc%2FWc21zgLORH1Hfb%2BTW0LXVCp1lOzskqxjapuvVl7rAm0ghzcFjyWm4eXu%2BOewrWELeUCB1dCsD%2BAMBBP2C96ZYOnGisOZnpWD%2BofuuygRgxn4NuxoKRtWbOR8k2%2B5Trd4Tt7%2BMJqN%2FWSok945oWyR2%2Fm0COv44DRjqVdTicmdJH0%2B8iN%2F34DyT95zgP83QqHi%2F478UP6lA04gg%2Fa%2FSz0McUbgAjqZfhvEkJVJwj3bHsu380XN0UP1XUgUYOyP9mfDvhQP5hvQC5ADzGymgrTi3a%2BHllSZ%2BeioLJuQujixtL4%2F0MUlIOGanbg5S13sv7coLCaQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 18:30:54,789 ERROR   Thread-16 :17174 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmp1qnk896dwandb/tbonvbwu-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/04o6n0t3/wandb-metadata.json?Expires=1689071453&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lZHcjGGd6%2FV0Pchqc%2FWc21zgLORH1Hfb%2BTW0LXVCp1lOzskqxjapuvVl7rAm0ghzcFjyWm4eXu%2BOewrWELeUCB1dCsD%2BAMBBP2C96ZYOnGisOZnpWD%2BofuuygRgxn4NuxoKRtWbOR8k2%2B5Trd4Tt7%2BMJqN%2FWSok945oWyR2%2Fm0COv44DRjqVdTicmdJH0%2B8iN%2F34DyT95zgP83QqHi%2F478UP6lA04gg%2Fa%2FSz0McUbgAjqZfhvEkJVJwj3bHsu380XN0UP1XUgUYOyP9mfDvhQP5hvQC5ADzGymgrTi3a%2BHllSZ%2BeioLJuQujixtL4%2F0MUlIOGanbg5S13sv7coLCaQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 18:30:56,197 INFO    Thread-17 :17174 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_183050-04o6n0t3/files/output.log
2023-07-10 18:30:56,287 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:30:58,197 INFO    Thread-17 :17174 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_183050-04o6n0t3/files/output.log
2023-07-10 18:31:01,470 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:31:03,164 DEBUG   SenderThread:17174 [sender.py:send():369] send: telemetry
2023-07-10 18:31:04,199 INFO    Thread-17 :17174 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_183050-04o6n0t3/files/output.log
2023-07-10 18:31:06,200 INFO    Thread-17 :17174 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_183050-04o6n0t3/files/output.log
2023-07-10 18:31:07,021 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:31:08,171 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 18:31:08,171 DEBUG   SenderThread:17174 [sender.py:send_request():396] send_request: stop_status
2023-07-10 18:31:10,201 INFO    Thread-17 :17174 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_183050-04o6n0t3/files/output.log
2023-07-10 18:31:12,404 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:31:17,404 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:31:22,410 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:31:23,171 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 18:31:23,171 DEBUG   SenderThread:17174 [sender.py:send_request():396] send_request: stop_status
2023-07-10 18:31:23,205 INFO    Thread-17 :17174 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_183050-04o6n0t3/files/config.yaml
2023-07-10 18:31:28,405 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:31:33,405 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:31:38,171 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 18:31:38,172 DEBUG   SenderThread:17174 [sender.py:send_request():396] send_request: stop_status
2023-07-10 18:31:38,407 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:31:43,408 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:31:48,409 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:31:52,392 DEBUG   SystemMonitor:17174 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-10 18:31:52,393 DEBUG   SenderThread:17174 [sender.py:send():369] send: stats
2023-07-10 18:31:53,171 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 18:31:53,172 DEBUG   SenderThread:17174 [sender.py:send_request():396] send_request: stop_status
2023-07-10 18:31:54,407 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:31:59,408 DEBUG   HandlerThread:17174 [handler.py:handle_request():144] handle_request: status_report
