2023-07-10 19:06:33,475 INFO    StreamThr :26648 [internal.py:wandb_internal():86] W&B internal server running at pid: 26648, started at: 2023-07-10 19:06:33.474995
2023-07-10 19:06:33,476 DEBUG   HandlerThread:26648 [handler.py:handle_request():144] handle_request: status
2023-07-10 19:06:33,477 INFO    WriterThread:26648 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190633-10pr2cwq/run-10pr2cwq.wandb
2023-07-10 19:06:33,477 DEBUG   SenderThread:26648 [sender.py:send():369] send: header
2023-07-10 19:06:33,477 DEBUG   SenderThread:26648 [sender.py:send():369] send: run
2023-07-10 19:06:34,310 INFO    SenderThread:26648 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190633-10pr2cwq/files
2023-07-10 19:06:34,311 INFO    SenderThread:26648 [sender.py:_start_run_threads():1100] run started: 10pr2cwq with start time 1688987193.475409
2023-07-10 19:06:34,311 DEBUG   SenderThread:26648 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:06:34,311 INFO    SenderThread:26648 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:06:34,316 DEBUG   HandlerThread:26648 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 19:06:34,316 DEBUG   SenderThread:26648 [sender.py:send_request():396] send_request: check_version
2023-07-10 19:06:34,492 DEBUG   HandlerThread:26648 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 19:06:34,496 DEBUG   HandlerThread:26648 [system_info.py:__init__():31] System info init
2023-07-10 19:06:34,496 DEBUG   HandlerThread:26648 [system_info.py:__init__():46] System info init done
2023-07-10 19:06:34,496 INFO    HandlerThread:26648 [system_monitor.py:start():181] Starting system monitor
2023-07-10 19:06:34,496 INFO    SystemMonitor:26648 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 19:06:34,496 INFO    HandlerThread:26648 [system_monitor.py:probe():201] Collecting system info
2023-07-10 19:06:34,496 INFO    SystemMonitor:26648 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 19:06:34,497 INFO    SystemMonitor:26648 [interfaces.py:start():190] Started disk monitoring
2023-07-10 19:06:34,497 INFO    SystemMonitor:26648 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 19:06:34,497 INFO    SystemMonitor:26648 [interfaces.py:start():190] Started memory monitoring
2023-07-10 19:06:34,498 INFO    SystemMonitor:26648 [interfaces.py:start():190] Started network monitoring
2023-07-10 19:06:34,511 DEBUG   HandlerThread:26648 [system_info.py:probe():195] Probing system
2023-07-10 19:06:34,514 DEBUG   HandlerThread:26648 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 19:06:34,514 DEBUG   HandlerThread:26648 [system_info.py:probe():240] Probing system done
2023-07-10 19:06:34,514 DEBUG   HandlerThread:26648 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T11:06:34.511067', 'startedAt': '2023-07-10T11:06:33.470515', 'docker': None, 'cuda': None, 'args': ('--phase', 'train', '--gpu_ids', '1'), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3577.6210416666668, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5100.346, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5099.928, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5048.948, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.1, 'min': 800.0, 'max': 5200.0}, {'current': 5102.355, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5010.269, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 4700.959, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.0181884765625}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-10 19:06:34,514 INFO    HandlerThread:26648 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 19:06:34,514 INFO    HandlerThread:26648 [system_monitor.py:probe():214] Publishing system info
2023-07-10 19:06:34,514 DEBUG   HandlerThread:26648 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 19:06:34,514 DEBUG   HandlerThread:26648 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 19:06:34,514 DEBUG   HandlerThread:26648 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 19:06:35,288 DEBUG   HandlerThread:26648 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 19:06:35,288 INFO    HandlerThread:26648 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 19:06:35,290 DEBUG   SenderThread:26648 [sender.py:send():369] send: files
2023-07-10 19:06:35,290 INFO    SenderThread:26648 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 19:06:35,293 DEBUG   HandlerThread:26648 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:06:35,293 DEBUG   SenderThread:26648 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:06:35,311 INFO    Thread-12 :26648 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190633-10pr2cwq/files/requirements.txt
2023-07-10 19:06:35,311 INFO    Thread-12 :26648 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190633-10pr2cwq/files/conda-environment.yaml
2023-07-10 19:06:35,311 INFO    Thread-12 :26648 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190633-10pr2cwq/files/wandb-summary.json
2023-07-10 19:06:35,311 INFO    Thread-12 :26648 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190633-10pr2cwq/files/wandb-metadata.json
2023-07-10 19:06:35,760 ERROR   wandb-upload_0:26648 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/10pr2cwq/wandb-metadata.json?Expires=1689073595&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HgfRteicfCLEP6L6PZLqVuZQXYgspVnfCbNJy6E22uEjKNbOBHu3Y5BEUsVkVzR7mceTtHosAidICxcHrkbLY8%2Fuz%2Bm3H09Bc%2B8n568BF3NLhYWpoHLrJL%2B1ZCkIvvjfxQvVyWJh2LZR2mLZMOuI1VJLmxNHxr0f9zjg1mB1IahFDjnnwla36PFwFUoPIJQEpnqylQzRzwneWioV6thDI9VNSdl8jL1ync3rwV2o%2F%2BLnWafRw3%2Fu22fXwyfYVpq9B9uHrghJniDuTzDuUHyu%2BhKXNsQIcPwGBEkR7O5mNuaQ2%2FMYKo%2BeEEah6pX%2FI2%2BylQqGkDa4bZ%2B8QiOm3WQLaA%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/10pr2cwq/wandb-metadata.json?Expires=1689073595&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HgfRteicfCLEP6L6PZLqVuZQXYgspVnfCbNJy6E22uEjKNbOBHu3Y5BEUsVkVzR7mceTtHosAidICxcHrkbLY8%2Fuz%2Bm3H09Bc%2B8n568BF3NLhYWpoHLrJL%2B1ZCkIvvjfxQvVyWJh2LZR2mLZMOuI1VJLmxNHxr0f9zjg1mB1IahFDjnnwla36PFwFUoPIJQEpnqylQzRzwneWioV6thDI9VNSdl8jL1ync3rwV2o%2F%2BLnWafRw3%2Fu22fXwyfYVpq9B9uHrghJniDuTzDuUHyu%2BhKXNsQIcPwGBEkR7O5mNuaQ2%2FMYKo%2BeEEah6pX%2FI2%2BylQqGkDa4bZ%2B8QiOm3WQLaA%3D%3D
2023-07-10 19:06:35,760 ERROR   wandb-upload_0:26648 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3687'}
2023-07-10 19:06:35,760 ERROR   wandb-upload_0:26648 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/10pr2cwq/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:06:35,851 DEBUG   SenderThread:26648 [sender.py:send():369] send: telemetry
2023-07-10 19:06:36,311 INFO    Thread-12 :26648 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190633-10pr2cwq/files/output.log
2023-07-10 19:06:37,534 ERROR   wandb-upload_0:26648 [upload_job.py:push():136] Failed to upload file: /tmp/tmpoagly2m9wandb/u2w5n2px-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/10pr2cwq/wandb-metadata.json?Expires=1689073595&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HgfRteicfCLEP6L6PZLqVuZQXYgspVnfCbNJy6E22uEjKNbOBHu3Y5BEUsVkVzR7mceTtHosAidICxcHrkbLY8%2Fuz%2Bm3H09Bc%2B8n568BF3NLhYWpoHLrJL%2B1ZCkIvvjfxQvVyWJh2LZR2mLZMOuI1VJLmxNHxr0f9zjg1mB1IahFDjnnwla36PFwFUoPIJQEpnqylQzRzwneWioV6thDI9VNSdl8jL1ync3rwV2o%2F%2BLnWafRw3%2Fu22fXwyfYVpq9B9uHrghJniDuTzDuUHyu%2BhKXNsQIcPwGBEkR7O5mNuaQ2%2FMYKo%2BeEEah6pX%2FI2%2BylQqGkDa4bZ%2B8QiOm3WQLaA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:06:37,749 ERROR   Thread-11 :26648 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpoagly2m9wandb/u2w5n2px-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/10pr2cwq/wandb-metadata.json?Expires=1689073595&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HgfRteicfCLEP6L6PZLqVuZQXYgspVnfCbNJy6E22uEjKNbOBHu3Y5BEUsVkVzR7mceTtHosAidICxcHrkbLY8%2Fuz%2Bm3H09Bc%2B8n568BF3NLhYWpoHLrJL%2B1ZCkIvvjfxQvVyWJh2LZR2mLZMOuI1VJLmxNHxr0f9zjg1mB1IahFDjnnwla36PFwFUoPIJQEpnqylQzRzwneWioV6thDI9VNSdl8jL1ync3rwV2o%2F%2BLnWafRw3%2Fu22fXwyfYVpq9B9uHrghJniDuTzDuUHyu%2BhKXNsQIcPwGBEkR7O5mNuaQ2%2FMYKo%2BeEEah6pX%2FI2%2BylQqGkDa4bZ%2B8QiOm3WQLaA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:06:38,312 INFO    Thread-12 :26648 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190633-10pr2cwq/files/output.log
2023-07-10 19:06:38,879 DEBUG   HandlerThread:26648 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:06:40,312 INFO    Thread-12 :26648 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190633-10pr2cwq/files/output.log
2023-07-10 19:06:43,556 DEBUG   SenderThread:26648 [sender.py:send():369] send: telemetry
2023-07-10 19:06:44,313 INFO    Thread-12 :26648 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190633-10pr2cwq/files/output.log
2023-07-10 19:06:44,621 DEBUG   HandlerThread:26648 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:06:46,314 INFO    Thread-12 :26648 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190633-10pr2cwq/files/output.log
2023-07-10 19:06:49,828 DEBUG   HandlerThread:26648 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:06:50,293 DEBUG   HandlerThread:26648 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:06:50,293 DEBUG   SenderThread:26648 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:06:50,315 INFO    Thread-12 :26648 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190633-10pr2cwq/files/output.log
2023-07-10 19:06:55,514 DEBUG   HandlerThread:26648 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:07:00,515 DEBUG   HandlerThread:26648 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:07:05,293 DEBUG   HandlerThread:26648 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:07:05,293 DEBUG   SenderThread:26648 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:07:06,513 DEBUG   HandlerThread:26648 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:07:07,318 INFO    Thread-12 :26648 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190633-10pr2cwq/files/config.yaml
2023-07-10 19:07:11,853 DEBUG   HandlerThread:26648 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:07:16,506 INFO    memory    :26648 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2023-07-10 19:07:16,506 DEBUG   SystemMonitor:26648 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-10 19:07:16,506 DEBUG   SystemMonitor:26648 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-07-10 19:07:16,506 DEBUG   SystemMonitor:26648 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-07-10 19:07:16,507 DEBUG   SenderThread:26648 [sender.py:send():369] send: stats
2023-07-10 19:07:17,499 INFO    MainThread:26648 [internal.py:handle_exit():76] Internal process exited
2023-07-10 19:07:17,508 DEBUG   HandlerThread:26648 [handler.py:handle_request():144] handle_request: status_report
