2023-07-11 13:50:15,556 INFO    StreamThr :109555 [internal.py:wandb_internal():86] W&B internal server running at pid: 109555, started at: 2023-07-11 13:50:15.555852
2023-07-11 13:50:15,560 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status
2023-07-11 13:50:15,561 INFO    WriterThread:109555 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/run-1qpovgts.wandb
2023-07-11 13:50:15,562 DEBUG   SenderThread:109555 [sender.py:send():369] send: header
2023-07-11 13:50:15,562 DEBUG   SenderThread:109555 [sender.py:send():369] send: run
2023-07-11 13:50:16,456 INFO    SenderThread:109555 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files
2023-07-11 13:50:16,456 INFO    SenderThread:109555 [sender.py:_start_run_threads():1100] run started: 1qpovgts with start time 1689054615.556149
2023-07-11 13:50:16,456 DEBUG   SenderThread:109555 [sender.py:send_request():396] send_request: summary_record
2023-07-11 13:50:16,456 INFO    SenderThread:109555 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-11 13:50:16,458 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: check_version
2023-07-11 13:50:16,458 DEBUG   SenderThread:109555 [sender.py:send_request():396] send_request: check_version
2023-07-11 13:50:16,652 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: run_start
2023-07-11 13:50:16,665 DEBUG   HandlerThread:109555 [system_info.py:__init__():31] System info init
2023-07-11 13:50:16,665 DEBUG   HandlerThread:109555 [system_info.py:__init__():46] System info init done
2023-07-11 13:50:16,665 INFO    HandlerThread:109555 [system_monitor.py:start():181] Starting system monitor
2023-07-11 13:50:16,665 INFO    SystemMonitor:109555 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-11 13:50:16,666 INFO    HandlerThread:109555 [system_monitor.py:probe():201] Collecting system info
2023-07-11 13:50:16,667 INFO    SystemMonitor:109555 [interfaces.py:start():190] Started cpu monitoring
2023-07-11 13:50:16,669 INFO    SystemMonitor:109555 [interfaces.py:start():190] Started disk monitoring
2023-07-11 13:50:16,669 INFO    SystemMonitor:109555 [interfaces.py:start():190] Started gpu monitoring
2023-07-11 13:50:16,670 INFO    SystemMonitor:109555 [interfaces.py:start():190] Started memory monitoring
2023-07-11 13:50:16,670 INFO    SystemMonitor:109555 [interfaces.py:start():190] Started network monitoring
2023-07-11 13:50:16,686 DEBUG   HandlerThread:109555 [system_info.py:probe():195] Probing system
2023-07-11 13:50:16,695 DEBUG   HandlerThread:109555 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-11 13:50:16,695 DEBUG   HandlerThread:109555 [system_info.py:probe():240] Probing system done
2023-07-11 13:50:16,696 DEBUG   HandlerThread:109555 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-11T05:50:16.686570', 'startedAt': '2023-07-11T05:50:15.542146', 'docker': None, 'cuda': None, 'args': ('--phase', 'train', '--gpu_ids', '1'), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 2073.477375, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2030.706, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2158.789, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1933.402, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1871.222, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 1995.74, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 2000.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2002.386, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.019886016845703125}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-11 13:50:16,696 INFO    HandlerThread:109555 [system_monitor.py:probe():211] Finished collecting system info
2023-07-11 13:50:16,696 INFO    HandlerThread:109555 [system_monitor.py:probe():214] Publishing system info
2023-07-11 13:50:16,696 DEBUG   HandlerThread:109555 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-11 13:50:16,696 DEBUG   HandlerThread:109555 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-11 13:50:16,697 DEBUG   HandlerThread:109555 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-11 13:50:17,457 INFO    Thread-12 :109555 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files/conda-environment.yaml
2023-07-11 13:50:17,457 INFO    Thread-12 :109555 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files/wandb-summary.json
2023-07-11 13:50:17,457 INFO    Thread-12 :109555 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files/requirements.txt
2023-07-11 13:50:17,675 DEBUG   HandlerThread:109555 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-11 13:50:17,675 INFO    HandlerThread:109555 [system_monitor.py:probe():216] Finished publishing system info
2023-07-11 13:50:17,677 DEBUG   SenderThread:109555 [sender.py:send():369] send: files
2023-07-11 13:50:17,677 INFO    SenderThread:109555 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-11 13:50:17,680 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 13:50:17,681 DEBUG   SenderThread:109555 [sender.py:send_request():396] send_request: stop_status
2023-07-11 13:50:18,129 ERROR   wandb-upload_0:109555 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/1qpovgts/wandb-metadata.json?Expires=1689141017&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bf7mz0xjnukij6D9%2F76p%2FEi28ryEreVopa5MFLoJ%2FS1Kb9jbVN3ocOZIVpLoZqPqbXeWCUABK4nfBRVsCxG8ipceQWKH4JOAjZvf3i8uAfcyco54idMheegE5enpw4p7t9wPqByUtgMN%2BM5fAW04jQDPem27sQfKcTye4EcKVrCJHyrGilEYjcAQkpDSrfbgdRXUn88Vh%2FEzSzDnkDgYz%2BCtKAiu%2FlECpgNjJ1IB5Fi4AMILHvdBVqJNkchqt6em6OcF4Cv8%2F4CXu6lm3Y4R7C78VjjK4cKgWIydX9olqB3uXyDtBNSpjRn8w%2FluOirGTFfCB%2BEi9Mu9XB4MNbJKHQ%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/1qpovgts/wandb-metadata.json?Expires=1689141017&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bf7mz0xjnukij6D9%2F76p%2FEi28ryEreVopa5MFLoJ%2FS1Kb9jbVN3ocOZIVpLoZqPqbXeWCUABK4nfBRVsCxG8ipceQWKH4JOAjZvf3i8uAfcyco54idMheegE5enpw4p7t9wPqByUtgMN%2BM5fAW04jQDPem27sQfKcTye4EcKVrCJHyrGilEYjcAQkpDSrfbgdRXUn88Vh%2FEzSzDnkDgYz%2BCtKAiu%2FlECpgNjJ1IB5Fi4AMILHvdBVqJNkchqt6em6OcF4Cv8%2F4CXu6lm3Y4R7C78VjjK4cKgWIydX9olqB3uXyDtBNSpjRn8w%2FluOirGTFfCB%2BEi9Mu9XB4MNbJKHQ%3D%3D
2023-07-11 13:50:18,129 ERROR   wandb-upload_0:109555 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3684'}
2023-07-11 13:50:18,129 ERROR   wandb-upload_0:109555 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/1qpovgts/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-11 13:50:18,329 DEBUG   SenderThread:109555 [sender.py:send():369] send: telemetry
2023-07-11 13:50:18,457 INFO    Thread-12 :109555 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files/conda-environment.yaml
2023-07-11 13:50:18,457 INFO    Thread-12 :109555 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files/output.log
2023-07-11 13:50:18,458 INFO    Thread-12 :109555 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files/wandb-metadata.json
2023-07-11 13:50:20,047 ERROR   wandb-upload_0:109555 [upload_job.py:push():136] Failed to upload file: /tmp/tmpp581gstwwandb/e18bezcq-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/1qpovgts/wandb-metadata.json?Expires=1689141017&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bf7mz0xjnukij6D9%2F76p%2FEi28ryEreVopa5MFLoJ%2FS1Kb9jbVN3ocOZIVpLoZqPqbXeWCUABK4nfBRVsCxG8ipceQWKH4JOAjZvf3i8uAfcyco54idMheegE5enpw4p7t9wPqByUtgMN%2BM5fAW04jQDPem27sQfKcTye4EcKVrCJHyrGilEYjcAQkpDSrfbgdRXUn88Vh%2FEzSzDnkDgYz%2BCtKAiu%2FlECpgNjJ1IB5Fi4AMILHvdBVqJNkchqt6em6OcF4Cv8%2F4CXu6lm3Y4R7C78VjjK4cKgWIydX9olqB3uXyDtBNSpjRn8w%2FluOirGTFfCB%2BEi9Mu9XB4MNbJKHQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 13:50:20,251 ERROR   Thread-11 :109555 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpp581gstwwandb/e18bezcq-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/1qpovgts/wandb-metadata.json?Expires=1689141017&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bf7mz0xjnukij6D9%2F76p%2FEi28ryEreVopa5MFLoJ%2FS1Kb9jbVN3ocOZIVpLoZqPqbXeWCUABK4nfBRVsCxG8ipceQWKH4JOAjZvf3i8uAfcyco54idMheegE5enpw4p7t9wPqByUtgMN%2BM5fAW04jQDPem27sQfKcTye4EcKVrCJHyrGilEYjcAQkpDSrfbgdRXUn88Vh%2FEzSzDnkDgYz%2BCtKAiu%2FlECpgNjJ1IB5Fi4AMILHvdBVqJNkchqt6em6OcF4Cv8%2F4CXu6lm3Y4R7C78VjjK4cKgWIydX9olqB3uXyDtBNSpjRn8w%2FluOirGTFfCB%2BEi9Mu9XB4MNbJKHQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 13:50:20,458 INFO    Thread-12 :109555 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files/output.log
2023-07-11 13:50:20,972 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:50:22,458 INFO    Thread-12 :109555 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files/output.log
2023-07-11 13:50:25,965 DEBUG   SenderThread:109555 [sender.py:send():369] send: telemetry
2023-07-11 13:50:26,027 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:50:26,460 INFO    Thread-12 :109555 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files/output.log
2023-07-11 13:50:28,460 INFO    Thread-12 :109555 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files/output.log
2023-07-11 13:50:31,547 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:50:32,461 INFO    Thread-12 :109555 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files/output.log
2023-07-11 13:50:32,680 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 13:50:32,681 DEBUG   SenderThread:109555 [sender.py:send_request():396] send_request: stop_status
2023-07-11 13:50:36,463 INFO    Thread-12 :109555 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files/output.log
2023-07-11 13:50:37,217 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:50:37,265 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: partial_history
2023-07-11 13:50:38,463 INFO    Thread-12 :109555 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files/output.log
2023-07-11 13:50:42,265 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:50:47,268 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:50:47,680 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 13:50:47,680 DEBUG   SenderThread:109555 [sender.py:send_request():396] send_request: stop_status
2023-07-11 13:50:48,465 INFO    Thread-12 :109555 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_135015-1qpovgts/files/config.yaml
2023-07-11 13:50:52,911 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:50:57,911 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:51:02,680 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 13:51:02,680 DEBUG   SenderThread:109555 [sender.py:send_request():396] send_request: stop_status
2023-07-11 13:51:02,911 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:51:07,912 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:51:12,912 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:51:16,670 DEBUG   SystemMonitor:109555 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-11 13:51:16,671 DEBUG   SenderThread:109555 [sender.py:send():369] send: stats
2023-07-11 13:51:17,680 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 13:51:17,680 DEBUG   SenderThread:109555 [sender.py:send_request():396] send_request: stop_status
2023-07-11 13:51:17,921 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:51:22,922 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:51:27,922 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:51:32,680 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 13:51:32,681 DEBUG   SenderThread:109555 [sender.py:send_request():396] send_request: stop_status
2023-07-11 13:51:32,960 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:51:37,960 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:51:42,961 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:51:46,672 DEBUG   SenderThread:109555 [sender.py:send():369] send: stats
2023-07-11 13:51:47,680 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 13:51:47,681 DEBUG   SenderThread:109555 [sender.py:send_request():396] send_request: stop_status
2023-07-11 13:51:48,923 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:51:53,923 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:51:58,924 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:52:02,680 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 13:52:02,681 DEBUG   SenderThread:109555 [sender.py:send_request():396] send_request: stop_status
2023-07-11 13:52:04,500 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:52:09,500 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:52:14,501 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:52:16,673 DEBUG   SenderThread:109555 [sender.py:send():369] send: stats
2023-07-11 13:52:17,680 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 13:52:17,681 DEBUG   SenderThread:109555 [sender.py:send_request():396] send_request: stop_status
2023-07-11 13:52:19,923 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:52:24,924 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:52:29,924 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:52:32,681 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 13:52:32,681 DEBUG   SenderThread:109555 [sender.py:send_request():396] send_request: stop_status
2023-07-11 13:52:35,912 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:52:40,913 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:52:45,913 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:52:46,673 DEBUG   SenderThread:109555 [sender.py:send():369] send: stats
2023-07-11 13:52:47,681 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 13:52:47,681 DEBUG   SenderThread:109555 [sender.py:send_request():396] send_request: stop_status
2023-07-11 13:52:50,922 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:52:55,923 DEBUG   HandlerThread:109555 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 13:52:58,676 INFO    MainThread:109555 [internal.py:handle_exit():76] Internal process exited
2023-07-11 13:52:58,711 INFO    memory    :109555 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2023-07-11 13:52:58,711 DEBUG   SystemMonitor:109555 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-07-11 13:52:58,712 DEBUG   SystemMonitor:109555 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-07-11 13:52:58,714 DEBUG   SenderThread:109555 [sender.py:send():369] send: stats
