2023-07-10 18:28:18,499 INFO    StreamThr :16307 [internal.py:wandb_internal():86] W&B internal server running at pid: 16307, started at: 2023-07-10 18:28:18.498996
2023-07-10 18:28:18,502 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status
2023-07-10 18:28:18,504 INFO    WriterThread:16307 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/run-bgqdjjov.wandb
2023-07-10 18:28:18,504 DEBUG   SenderThread:16307 [sender.py:send():369] send: header
2023-07-10 18:28:18,504 DEBUG   SenderThread:16307 [sender.py:send():369] send: run
2023-07-10 18:28:19,407 INFO    SenderThread:16307 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files
2023-07-10 18:28:19,408 INFO    SenderThread:16307 [sender.py:_start_run_threads():1100] run started: bgqdjjov with start time 1688984898.497532
2023-07-10 18:28:19,408 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: summary_record
2023-07-10 18:28:19,408 INFO    SenderThread:16307 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 18:28:19,413 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 18:28:19,414 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: check_version
2023-07-10 18:28:19,596 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 18:28:19,600 DEBUG   HandlerThread:16307 [system_info.py:__init__():31] System info init
2023-07-10 18:28:19,600 DEBUG   HandlerThread:16307 [system_info.py:__init__():46] System info init done
2023-07-10 18:28:19,600 INFO    HandlerThread:16307 [system_monitor.py:start():181] Starting system monitor
2023-07-10 18:28:19,601 INFO    SystemMonitor:16307 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 18:28:19,601 INFO    HandlerThread:16307 [system_monitor.py:probe():201] Collecting system info
2023-07-10 18:28:19,602 INFO    SystemMonitor:16307 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 18:28:19,603 INFO    SystemMonitor:16307 [interfaces.py:start():190] Started disk monitoring
2023-07-10 18:28:19,604 INFO    SystemMonitor:16307 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 18:28:19,605 INFO    SystemMonitor:16307 [interfaces.py:start():190] Started memory monitoring
2023-07-10 18:28:19,606 INFO    SystemMonitor:16307 [interfaces.py:start():190] Started network monitoring
2023-07-10 18:28:19,616 DEBUG   HandlerThread:16307 [system_info.py:probe():195] Probing system
2023-07-10 18:28:19,620 DEBUG   HandlerThread:16307 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 18:28:19,620 DEBUG   HandlerThread:16307 [system_info.py:probe():240] Probing system done
2023-07-10 18:28:19,620 DEBUG   HandlerThread:16307 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T10:28:19.616746', 'startedAt': '2023-07-10T10:28:18.489871', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3730.8603333333335, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5101.079, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5099.947, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5057.587, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 3681.56, 'min': 800.0, 'max': 4100.0}, {'current': 3707.73, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.0178375244140625}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-10 18:28:19,621 INFO    HandlerThread:16307 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 18:28:19,621 INFO    HandlerThread:16307 [system_monitor.py:probe():214] Publishing system info
2023-07-10 18:28:19,621 DEBUG   HandlerThread:16307 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 18:28:19,622 DEBUG   HandlerThread:16307 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 18:28:19,622 DEBUG   HandlerThread:16307 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 18:28:20,385 DEBUG   HandlerThread:16307 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 18:28:20,387 INFO    HandlerThread:16307 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 18:28:20,389 DEBUG   SenderThread:16307 [sender.py:send():369] send: files
2023-07-10 18:28:20,390 INFO    SenderThread:16307 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 18:28:20,396 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 18:28:20,396 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: stop_status
2023-07-10 18:28:20,410 INFO    Thread-17 :16307 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/wandb-metadata.json
2023-07-10 18:28:20,411 INFO    Thread-17 :16307 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/wandb-summary.json
2023-07-10 18:28:20,411 INFO    Thread-17 :16307 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/requirements.txt
2023-07-10 18:28:20,411 INFO    Thread-17 :16307 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/conda-environment.yaml
2023-07-10 18:28:20,854 ERROR   wandb-upload_0:16307 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/bgqdjjov/wandb-metadata.json?Expires=1689071300&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=aLTMVDRy5ab8C1YfAUoYIRExtBkyzei%2Bb1C4DE0tJjTg0%2Bl1JQI1g7Ra3bc5S5%2FbUSXK%2FzWq7GwqRY%2B7SxAunrRVaStP%2FYHboFgokqC2%2Fle3FgUOJ3SCvOX2R%2FzTxxpjz9xtKW9K7%2F3ubl%2FxKSlbv1jXouyZDTcwH%2FRJDBtXGtxwMo8uSHw%2FXy71QHDmYLWw2yZLXhtwSCNXRCq%2Fi9KQmshvy5ON%2Fu6XWKR8b49KaF24JRNvsA68FlXbrNGCUJnO0Flg%2BKHDB4%2Fvudwi2mngDk10ir25%2FbvD2kuwD9qC79CCrsANGziDVNkvFLMNMDRPDG6cByCeRveGNm69yGtK1g%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/bgqdjjov/wandb-metadata.json?Expires=1689071300&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=aLTMVDRy5ab8C1YfAUoYIRExtBkyzei%2Bb1C4DE0tJjTg0%2Bl1JQI1g7Ra3bc5S5%2FbUSXK%2FzWq7GwqRY%2B7SxAunrRVaStP%2FYHboFgokqC2%2Fle3FgUOJ3SCvOX2R%2FzTxxpjz9xtKW9K7%2F3ubl%2FxKSlbv1jXouyZDTcwH%2FRJDBtXGtxwMo8uSHw%2FXy71QHDmYLWw2yZLXhtwSCNXRCq%2Fi9KQmshvy5ON%2Fu6XWKR8b49KaF24JRNvsA68FlXbrNGCUJnO0Flg%2BKHDB4%2Fvudwi2mngDk10ir25%2FbvD2kuwD9qC79CCrsANGziDVNkvFLMNMDRPDG6cByCeRveGNm69yGtK1g%3D%3D
2023-07-10 18:28:20,855 ERROR   wandb-upload_0:16307 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3612'}
2023-07-10 18:28:20,855 ERROR   wandb-upload_0:16307 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/bgqdjjov/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 18:28:20,944 DEBUG   SenderThread:16307 [sender.py:send():369] send: telemetry
2023-07-10 18:28:21,407 INFO    Thread-17 :16307 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/output.log
2023-07-10 18:28:21,429 ERROR   wandb-upload_0:16307 [upload_job.py:push():136] Failed to upload file: /tmp/tmpqg3io2w9wandb/g4lt3ute-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/bgqdjjov/wandb-metadata.json?Expires=1689071300&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=aLTMVDRy5ab8C1YfAUoYIRExtBkyzei%2Bb1C4DE0tJjTg0%2Bl1JQI1g7Ra3bc5S5%2FbUSXK%2FzWq7GwqRY%2B7SxAunrRVaStP%2FYHboFgokqC2%2Fle3FgUOJ3SCvOX2R%2FzTxxpjz9xtKW9K7%2F3ubl%2FxKSlbv1jXouyZDTcwH%2FRJDBtXGtxwMo8uSHw%2FXy71QHDmYLWw2yZLXhtwSCNXRCq%2Fi9KQmshvy5ON%2Fu6XWKR8b49KaF24JRNvsA68FlXbrNGCUJnO0Flg%2BKHDB4%2Fvudwi2mngDk10ir25%2FbvD2kuwD9qC79CCrsANGziDVNkvFLMNMDRPDG6cByCeRveGNm69yGtK1g%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 18:28:21,652 ERROR   Thread-16 :16307 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpqg3io2w9wandb/g4lt3ute-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/bgqdjjov/wandb-metadata.json?Expires=1689071300&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=aLTMVDRy5ab8C1YfAUoYIRExtBkyzei%2Bb1C4DE0tJjTg0%2Bl1JQI1g7Ra3bc5S5%2FbUSXK%2FzWq7GwqRY%2B7SxAunrRVaStP%2FYHboFgokqC2%2Fle3FgUOJ3SCvOX2R%2FzTxxpjz9xtKW9K7%2F3ubl%2FxKSlbv1jXouyZDTcwH%2FRJDBtXGtxwMo8uSHw%2FXy71QHDmYLWw2yZLXhtwSCNXRCq%2Fi9KQmshvy5ON%2Fu6XWKR8b49KaF24JRNvsA68FlXbrNGCUJnO0Flg%2BKHDB4%2Fvudwi2mngDk10ir25%2FbvD2kuwD9qC79CCrsANGziDVNkvFLMNMDRPDG6cByCeRveGNm69yGtK1g%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 18:28:23,408 INFO    Thread-17 :16307 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/output.log
2023-07-10 18:28:23,554 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:28:25,409 INFO    Thread-17 :16307 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/output.log
2023-07-10 18:28:28,737 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:28:30,518 DEBUG   SenderThread:16307 [sender.py:send():369] send: telemetry
2023-07-10 18:28:31,411 INFO    Thread-17 :16307 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/output.log
2023-07-10 18:28:33,411 INFO    Thread-17 :16307 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/output.log
2023-07-10 18:28:34,363 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:28:35,395 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 18:28:35,395 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: stop_status
2023-07-10 18:28:35,412 INFO    Thread-17 :16307 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/output.log
2023-07-10 18:28:39,612 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:28:44,613 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:28:49,619 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:28:50,395 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 18:28:50,396 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: stop_status
2023-07-10 18:28:50,417 INFO    Thread-17 :16307 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/config.yaml
2023-07-10 18:28:55,624 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:29:00,624 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:29:05,395 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 18:29:05,396 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: stop_status
2023-07-10 18:29:06,617 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:29:11,618 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:29:16,618 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:29:19,606 DEBUG   SystemMonitor:16307 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-10 18:29:19,608 DEBUG   SenderThread:16307 [sender.py:send():369] send: stats
2023-07-10 18:29:20,395 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 18:29:20,396 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: stop_status
2023-07-10 18:29:21,630 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:29:26,631 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:29:29,838 DEBUG   SenderThread:16307 [sender.py:send():369] send: exit
2023-07-10 18:29:29,838 INFO    SenderThread:16307 [sender.py:send_exit():574] handling exit code: 255
2023-07-10 18:29:29,838 INFO    SenderThread:16307 [sender.py:send_exit():576] handling runtime: 70
2023-07-10 18:29:29,841 INFO    SenderThread:16307 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 18:29:29,841 INFO    SenderThread:16307 [sender.py:send_exit():582] send defer
2023-07-10 18:29:29,841 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: defer
2023-07-10 18:29:29,841 INFO    HandlerThread:16307 [handler.py:handle_request_defer():170] handle defer: 0
2023-07-10 18:29:29,842 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: defer
2023-07-10 18:29:29,842 INFO    SenderThread:16307 [sender.py:send_request_defer():598] handle sender defer: 0
2023-07-10 18:29:29,842 INFO    SenderThread:16307 [sender.py:transition_state():602] send defer: 1
2023-07-10 18:29:29,842 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: defer
2023-07-10 18:29:29,842 INFO    HandlerThread:16307 [handler.py:handle_request_defer():170] handle defer: 1
2023-07-10 18:29:29,842 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: defer
2023-07-10 18:29:29,842 INFO    SenderThread:16307 [sender.py:send_request_defer():598] handle sender defer: 1
2023-07-10 18:29:29,843 INFO    SenderThread:16307 [sender.py:transition_state():602] send defer: 2
2023-07-10 18:29:29,843 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: defer
2023-07-10 18:29:29,843 INFO    HandlerThread:16307 [handler.py:handle_request_defer():170] handle defer: 2
2023-07-10 18:29:29,843 INFO    HandlerThread:16307 [system_monitor.py:finish():190] Stopping system monitor
2023-07-10 18:29:29,844 DEBUG   SystemMonitor:16307 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-07-10 18:29:29,844 DEBUG   SystemMonitor:16307 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-07-10 18:29:29,845 INFO    HandlerThread:16307 [interfaces.py:finish():202] Joined cpu monitor
2023-07-10 18:29:29,845 INFO    HandlerThread:16307 [interfaces.py:finish():202] Joined disk monitor
2023-07-10 18:29:29,894 INFO    HandlerThread:16307 [interfaces.py:finish():202] Joined gpu monitor
2023-07-10 18:29:29,895 INFO    HandlerThread:16307 [interfaces.py:finish():202] Joined memory monitor
2023-07-10 18:29:29,895 INFO    HandlerThread:16307 [interfaces.py:finish():202] Joined network monitor
2023-07-10 18:29:29,895 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: defer
2023-07-10 18:29:29,895 INFO    SenderThread:16307 [sender.py:send_request_defer():598] handle sender defer: 2
2023-07-10 18:29:29,896 INFO    SenderThread:16307 [sender.py:transition_state():602] send defer: 3
2023-07-10 18:29:29,896 DEBUG   SenderThread:16307 [sender.py:send():369] send: stats
2023-07-10 18:29:29,896 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: defer
2023-07-10 18:29:29,896 INFO    HandlerThread:16307 [handler.py:handle_request_defer():170] handle defer: 3
2023-07-10 18:29:29,897 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: defer
2023-07-10 18:29:29,897 INFO    SenderThread:16307 [sender.py:send_request_defer():598] handle sender defer: 3
2023-07-10 18:29:29,897 INFO    SenderThread:16307 [sender.py:transition_state():602] send defer: 4
2023-07-10 18:29:29,897 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: defer
2023-07-10 18:29:29,897 INFO    HandlerThread:16307 [handler.py:handle_request_defer():170] handle defer: 4
2023-07-10 18:29:29,898 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: defer
2023-07-10 18:29:29,898 INFO    SenderThread:16307 [sender.py:send_request_defer():598] handle sender defer: 4
2023-07-10 18:29:29,898 INFO    SenderThread:16307 [sender.py:transition_state():602] send defer: 5
2023-07-10 18:29:29,898 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: defer
2023-07-10 18:29:29,898 INFO    HandlerThread:16307 [handler.py:handle_request_defer():170] handle defer: 5
2023-07-10 18:29:29,899 DEBUG   SenderThread:16307 [sender.py:send():369] send: summary
2023-07-10 18:29:29,899 INFO    SenderThread:16307 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 18:29:29,899 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: defer
2023-07-10 18:29:29,899 INFO    SenderThread:16307 [sender.py:send_request_defer():598] handle sender defer: 5
2023-07-10 18:29:29,899 INFO    SenderThread:16307 [sender.py:transition_state():602] send defer: 6
2023-07-10 18:29:29,899 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: defer
2023-07-10 18:29:29,899 INFO    HandlerThread:16307 [handler.py:handle_request_defer():170] handle defer: 6
2023-07-10 18:29:29,900 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: defer
2023-07-10 18:29:29,900 INFO    SenderThread:16307 [sender.py:send_request_defer():598] handle sender defer: 6
2023-07-10 18:29:29,900 INFO    SenderThread:16307 [sender.py:transition_state():602] send defer: 7
2023-07-10 18:29:29,900 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:29:29,900 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: defer
2023-07-10 18:29:29,900 INFO    HandlerThread:16307 [handler.py:handle_request_defer():170] handle defer: 7
2023-07-10 18:29:29,900 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: defer
2023-07-10 18:29:29,900 INFO    SenderThread:16307 [sender.py:send_request_defer():598] handle sender defer: 7
2023-07-10 18:29:30,429 INFO    Thread-17 :16307 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/wandb-summary.json
2023-07-10 18:29:30,838 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: poll_exit
2023-07-10 18:29:31,430 INFO    Thread-17 :16307 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/output.log
2023-07-10 18:29:33,040 INFO    SenderThread:16307 [sender.py:transition_state():602] send defer: 8
2023-07-10 18:29:33,040 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: poll_exit
2023-07-10 18:29:33,040 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: defer
2023-07-10 18:29:33,041 INFO    HandlerThread:16307 [handler.py:handle_request_defer():170] handle defer: 8
2023-07-10 18:29:33,041 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: defer
2023-07-10 18:29:33,041 INFO    SenderThread:16307 [sender.py:send_request_defer():598] handle sender defer: 8
2023-07-10 18:29:33,042 INFO    SenderThread:16307 [job_builder.py:build():232] Attempting to build job artifact
2023-07-10 18:29:33,042 INFO    SenderThread:16307 [job_builder.py:build():266] no source found
2023-07-10 18:29:33,042 INFO    SenderThread:16307 [sender.py:transition_state():602] send defer: 9
2023-07-10 18:29:33,042 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: defer
2023-07-10 18:29:33,042 INFO    HandlerThread:16307 [handler.py:handle_request_defer():170] handle defer: 9
2023-07-10 18:29:33,042 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: defer
2023-07-10 18:29:33,042 INFO    SenderThread:16307 [sender.py:send_request_defer():598] handle sender defer: 9
2023-07-10 18:29:33,042 INFO    SenderThread:16307 [dir_watcher.py:finish():359] shutting down directory watcher
2023-07-10 18:29:33,430 INFO    Thread-17 :16307 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/output.log
2023-07-10 18:29:33,431 INFO    SenderThread:16307 [dir_watcher.py:finish():389] scan: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files
2023-07-10 18:29:33,431 INFO    SenderThread:16307 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/wandb-metadata.json wandb-metadata.json
2023-07-10 18:29:33,431 INFO    SenderThread:16307 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/config.yaml config.yaml
2023-07-10 18:29:33,432 INFO    SenderThread:16307 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/requirements.txt requirements.txt
2023-07-10 18:29:33,432 INFO    SenderThread:16307 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/wandb-summary.json wandb-summary.json
2023-07-10 18:29:33,432 INFO    SenderThread:16307 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/conda-environment.yaml conda-environment.yaml
2023-07-10 18:29:33,432 INFO    SenderThread:16307 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/output.log output.log
2023-07-10 18:29:33,432 INFO    SenderThread:16307 [sender.py:transition_state():602] send defer: 10
2023-07-10 18:29:33,432 DEBUG   HandlerThread:16307 [handler.py:handle_request():144] handle_request: defer
2023-07-10 18:29:33,432 INFO    HandlerThread:16307 [handler.py:handle_request_defer():170] handle defer: 10
2023-07-10 18:29:33,436 DEBUG   SenderThread:16307 [sender.py:send_request():396] send_request: defer
2023-07-10 18:29:33,437 INFO    SenderThread:16307 [sender.py:send_request_defer():598] handle sender defer: 10
2023-07-10 18:29:33,437 INFO    SenderThread:16307 [file_pusher.py:finish():159] shutting down file pusher
2023-07-10 18:29:33,898 ERROR   wandb-upload_1:16307 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/bgqdjjov/requirements.txt?Expires=1689071373&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cCRZ%2FOmHk%2FOCe9ZTAdnPJwSrBYHMYQzH2LdsAFpQTkKTI%2FxDLCzxr7wJXqMbfP28EI%2FglN%2Fkqo1y%2F3KSLEMT6%2FkUYeEWiHOmIXDcVsVI13bd%2BINWiDMGLBkT1a96iPvN723uJflW21IoCgK4JTG8OW2Sh90u5YvNOKlHIsLAFfAzomeVzFsky8RVO1Fz089DPnbpwdrnr23deLujNGNsnQNWZ3Q1QVv%2Ft88EilbTW0LkIkpG3StodT%2BXHxOFm4Ix%2FAgMqqQIK5MncSxswgEfOtV2g1hoEO2yOdSDc6mYMIQ5%2Brdn6Vfw4ATdmqPLmlVQapKw0lmSjmSqmdHYehQLkA%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/bgqdjjov/requirements.txt?Expires=1689071373&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cCRZ%2FOmHk%2FOCe9ZTAdnPJwSrBYHMYQzH2LdsAFpQTkKTI%2FxDLCzxr7wJXqMbfP28EI%2FglN%2Fkqo1y%2F3KSLEMT6%2FkUYeEWiHOmIXDcVsVI13bd%2BINWiDMGLBkT1a96iPvN723uJflW21IoCgK4JTG8OW2Sh90u5YvNOKlHIsLAFfAzomeVzFsky8RVO1Fz089DPnbpwdrnr23deLujNGNsnQNWZ3Q1QVv%2Ft88EilbTW0LkIkpG3StodT%2BXHxOFm4Ix%2FAgMqqQIK5MncSxswgEfOtV2g1hoEO2yOdSDc6mYMIQ5%2Brdn6Vfw4ATdmqPLmlVQapKw0lmSjmSqmdHYehQLkA%3D%3D
2023-07-10 18:29:33,898 ERROR   wandb-upload_1:16307 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '926'}
2023-07-10 18:29:33,898 ERROR   wandb-upload_1:16307 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/bgqdjjov/requirements.txt</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 18:29:33,904 ERROR   wandb-upload_0:16307 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/bgqdjjov/config.yaml?Expires=1689071373&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Rv91%2BS8PqoCm9%2BbunQlApe264rtz6YRJi3SQlwuoE5fITuOJYf7Ip6RRe1CXaceORNPAtDyFjg1JguuU8Nwz3fcxNmTSplXdmINXOxMMHWrl918Qd3T19nuGh7wIqZ7XWONz2fBJByouYvDva3Y6M7%2BtsDH0UCW8ncdz%2BjulSR2bnR1LjQreqYT%2FrD3VwdWSy%2BY7QexYUI2U3WjqP5bVtgJEyR6A9zxz72sI1YhUsTybqqSYOigqFZb3Mqn6v7MF%2BpQJ7zlH3kkTbperaZJQNcqxi5tRTPYnp%2BWE2hd5hsItz5eRdnaVZV8jgV3OaUoJgrrDc9NYIZdAj1Q3zhB3CA%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/bgqdjjov/config.yaml?Expires=1689071373&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Rv91%2BS8PqoCm9%2BbunQlApe264rtz6YRJi3SQlwuoE5fITuOJYf7Ip6RRe1CXaceORNPAtDyFjg1JguuU8Nwz3fcxNmTSplXdmINXOxMMHWrl918Qd3T19nuGh7wIqZ7XWONz2fBJByouYvDva3Y6M7%2BtsDH0UCW8ncdz%2BjulSR2bnR1LjQreqYT%2FrD3VwdWSy%2BY7QexYUI2U3WjqP5bVtgJEyR6A9zxz72sI1YhUsTybqqSYOigqFZb3Mqn6v7MF%2BpQJ7zlH3kkTbperaZJQNcqxi5tRTPYnp%2BWE2hd5hsItz5eRdnaVZV8jgV3OaUoJgrrDc9NYIZdAj1Q3zhB3CA%3D%3D
2023-07-10 18:29:33,904 ERROR   wandb-upload_0:16307 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '526'}
2023-07-10 18:29:33,904 ERROR   wandb-upload_0:16307 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/bgqdjjov/config.yaml</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 18:29:34,334 ERROR   wandb-upload_1:16307 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/requirements.txt
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/bgqdjjov/requirements.txt?Expires=1689071373&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cCRZ%2FOmHk%2FOCe9ZTAdnPJwSrBYHMYQzH2LdsAFpQTkKTI%2FxDLCzxr7wJXqMbfP28EI%2FglN%2Fkqo1y%2F3KSLEMT6%2FkUYeEWiHOmIXDcVsVI13bd%2BINWiDMGLBkT1a96iPvN723uJflW21IoCgK4JTG8OW2Sh90u5YvNOKlHIsLAFfAzomeVzFsky8RVO1Fz089DPnbpwdrnr23deLujNGNsnQNWZ3Q1QVv%2Ft88EilbTW0LkIkpG3StodT%2BXHxOFm4Ix%2FAgMqqQIK5MncSxswgEfOtV2g1hoEO2yOdSDc6mYMIQ5%2Brdn6Vfw4ATdmqPLmlVQapKw0lmSjmSqmdHYehQLkA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 18:29:34,335 ERROR   wandb-upload_0:16307 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_182818-bgqdjjov/files/config.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/bgqdjjov/config.yaml?Expires=1689071373&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Rv91%2BS8PqoCm9%2BbunQlApe264rtz6YRJi3SQlwuoE5fITuOJYf7Ip6RRe1CXaceORNPAtDyFjg1JguuU8Nwz3fcxNmTSplXdmINXOxMMHWrl918Qd3T19nuGh7wIqZ7XWONz2fBJByouYvDva3Y6M7%2BtsDH0UCW8ncdz%2BjulSR2bnR1LjQreqYT%2FrD3VwdWSy%2BY7QexYUI2U3WjqP5bVtgJEyR6A9zxz72sI1YhUsTybqqSYOigqFZb3Mqn6v7MF%2BpQJ7zlH3kkTbperaZJQNcqxi5tRTPYnp%2BWE2hd5hsItz5eRdnaVZV8jgV3OaUoJgrrDc9NYIZdAj1Q3zhB3CA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
