2023-07-10 19:34:48,577 INFO    StreamThr :30284 [internal.py:wandb_internal():86] W&B internal server running at pid: 30284, started at: 2023-07-10 19:34:48.577379
2023-07-10 19:34:48,578 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status
2023-07-10 19:34:48,580 INFO    WriterThread:30284 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/run-g7dnlenp.wandb
2023-07-10 19:34:48,580 DEBUG   SenderThread:30284 [sender.py:send():369] send: header
2023-07-10 19:34:48,580 DEBUG   SenderThread:30284 [sender.py:send():369] send: run
2023-07-10 19:34:49,423 INFO    SenderThread:30284 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files
2023-07-10 19:34:49,423 INFO    SenderThread:30284 [sender.py:_start_run_threads():1100] run started: g7dnlenp with start time 1688988888.577705
2023-07-10 19:34:49,425 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:34:49,425 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:34:49,428 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 19:34:49,429 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: check_version
2023-07-10 19:34:49,606 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 19:34:49,610 DEBUG   HandlerThread:30284 [system_info.py:__init__():31] System info init
2023-07-10 19:34:49,611 DEBUG   HandlerThread:30284 [system_info.py:__init__():46] System info init done
2023-07-10 19:34:49,611 INFO    HandlerThread:30284 [system_monitor.py:start():181] Starting system monitor
2023-07-10 19:34:49,611 INFO    SystemMonitor:30284 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 19:34:49,611 INFO    HandlerThread:30284 [system_monitor.py:probe():201] Collecting system info
2023-07-10 19:34:49,611 INFO    SystemMonitor:30284 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 19:34:49,612 INFO    SystemMonitor:30284 [interfaces.py:start():190] Started disk monitoring
2023-07-10 19:34:49,613 INFO    SystemMonitor:30284 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 19:34:49,613 INFO    SystemMonitor:30284 [interfaces.py:start():190] Started memory monitoring
2023-07-10 19:34:49,614 INFO    SystemMonitor:30284 [interfaces.py:start():190] Started network monitoring
2023-07-10 19:34:49,631 DEBUG   HandlerThread:30284 [system_info.py:probe():195] Probing system
2023-07-10 19:34:49,634 DEBUG   HandlerThread:30284 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 19:34:49,634 DEBUG   HandlerThread:30284 [system_info.py:probe():240] Probing system done
2023-07-10 19:34:49,634 DEBUG   HandlerThread:30284 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T11:34:49.631250', 'startedAt': '2023-07-10T11:34:48.572563', 'docker': None, 'cuda': None, 'args': ('--phase', 'train', '--gpu_ids', '1'), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3098.2976249999997, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5099.507, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5098.609, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5098.298, 'min': 800.0, 'max': 5100.0}, {'current': 5066.879, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5098.383, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5099.987, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5097.48, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.018260955810546875}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-10 19:34:49,635 INFO    HandlerThread:30284 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 19:34:49,635 INFO    HandlerThread:30284 [system_monitor.py:probe():214] Publishing system info
2023-07-10 19:34:49,635 DEBUG   HandlerThread:30284 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 19:34:49,635 DEBUG   HandlerThread:30284 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 19:34:49,635 DEBUG   HandlerThread:30284 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 19:34:50,424 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/requirements.txt
2023-07-10 19:34:50,425 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:34:50,425 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/conda-environment.yaml
2023-07-10 19:34:50,509 DEBUG   HandlerThread:30284 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 19:34:50,510 INFO    HandlerThread:30284 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 19:34:50,511 DEBUG   SenderThread:30284 [sender.py:send():369] send: files
2023-07-10 19:34:50,511 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 19:34:50,514 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:34:50,514 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:34:50,981 ERROR   wandb-upload_0:30284 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/wandb-metadata.json?Expires=1689075290&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=sKSVKqjuMBiBUKtFioumOq1PYnPgryQHTSJoBhDPZOEtiRm3MjISoJTZfq0AhVf27sufgDfeIwKS0Ppw%2F8dQeeQS%2FGJAVye7Cj0Z61hdg8FCbbJQKY4TnshYGcUlfgYohcF730xDi9nSusIokcyBTuGl%2B19V%2Fb%2FE%2BXuzZLxoed1l6kGTCuCqXvdz7D1UEwK4DDJn3st6ABsQCq%2FcqhyhQ%2FZVqAo8eO75P7Uw1kpXIiuxgwfskUJjAansYgc2%2F7dufURxCvIFM9bdo22iiFQd1k%2FXytaizefetPzeYzC7RP28cAov6MrOf42sDHojx4mSq0uPxSBp3TkbRt%2Fb7zjrRw%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/wandb-metadata.json?Expires=1689075290&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=sKSVKqjuMBiBUKtFioumOq1PYnPgryQHTSJoBhDPZOEtiRm3MjISoJTZfq0AhVf27sufgDfeIwKS0Ppw%2F8dQeeQS%2FGJAVye7Cj0Z61hdg8FCbbJQKY4TnshYGcUlfgYohcF730xDi9nSusIokcyBTuGl%2B19V%2Fb%2FE%2BXuzZLxoed1l6kGTCuCqXvdz7D1UEwK4DDJn3st6ABsQCq%2FcqhyhQ%2FZVqAo8eO75P7Uw1kpXIiuxgwfskUJjAansYgc2%2F7dufURxCvIFM9bdo22iiFQd1k%2FXytaizefetPzeYzC7RP28cAov6MrOf42sDHojx4mSq0uPxSBp3TkbRt%2Fb7zjrRw%3D%3D
2023-07-10 19:34:50,981 ERROR   wandb-upload_0:30284 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3693'}
2023-07-10 19:34:50,981 ERROR   wandb-upload_0:30284 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:34:51,056 DEBUG   SenderThread:30284 [sender.py:send():369] send: telemetry
2023-07-10 19:34:51,424 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:34:51,424 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-metadata.json
2023-07-10 19:34:51,566 ERROR   wandb-upload_0:30284 [upload_job.py:push():136] Failed to upload file: /tmp/tmpo1s53xppwandb/pnodaswd-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/wandb-metadata.json?Expires=1689075290&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=sKSVKqjuMBiBUKtFioumOq1PYnPgryQHTSJoBhDPZOEtiRm3MjISoJTZfq0AhVf27sufgDfeIwKS0Ppw%2F8dQeeQS%2FGJAVye7Cj0Z61hdg8FCbbJQKY4TnshYGcUlfgYohcF730xDi9nSusIokcyBTuGl%2B19V%2Fb%2FE%2BXuzZLxoed1l6kGTCuCqXvdz7D1UEwK4DDJn3st6ABsQCq%2FcqhyhQ%2FZVqAo8eO75P7Uw1kpXIiuxgwfskUJjAansYgc2%2F7dufURxCvIFM9bdo22iiFQd1k%2FXytaizefetPzeYzC7RP28cAov6MrOf42sDHojx4mSq0uPxSBp3TkbRt%2Fb7zjrRw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:34:51,783 ERROR   Thread-11 :30284 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpo1s53xppwandb/pnodaswd-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/wandb-metadata.json?Expires=1689075290&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=sKSVKqjuMBiBUKtFioumOq1PYnPgryQHTSJoBhDPZOEtiRm3MjISoJTZfq0AhVf27sufgDfeIwKS0Ppw%2F8dQeeQS%2FGJAVye7Cj0Z61hdg8FCbbJQKY4TnshYGcUlfgYohcF730xDi9nSusIokcyBTuGl%2B19V%2Fb%2FE%2BXuzZLxoed1l6kGTCuCqXvdz7D1UEwK4DDJn3st6ABsQCq%2FcqhyhQ%2FZVqAo8eO75P7Uw1kpXIiuxgwfskUJjAansYgc2%2F7dufURxCvIFM9bdo22iiFQd1k%2FXytaizefetPzeYzC7RP28cAov6MrOf42sDHojx4mSq0uPxSBp3TkbRt%2Fb7zjrRw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:34:53,425 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:34:53,793 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:34:55,425 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:34:58,880 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:34:58,981 DEBUG   SenderThread:30284 [sender.py:send():369] send: telemetry
2023-07-10 19:34:59,426 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:35:01,427 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:35:04,376 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:35:05,428 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:35:05,513 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:35:05,514 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:35:09,729 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:35:14,729 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:35:19,732 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:35:20,431 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/config.yaml
2023-07-10 19:35:20,514 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:35:20,514 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:35:25,741 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:35:30,742 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:35:35,514 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:35:35,514 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:35:35,770 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:35:36,745 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:35:36,746 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:35:36,746 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:35:36,747 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:35:37,435 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:35:39,435 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:35:41,748 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:35:46,749 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:35:49,614 DEBUG   SystemMonitor:30284 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-10 19:35:49,615 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:35:50,514 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:35:50,514 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:35:52,741 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:35:57,742 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:36:02,743 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:36:05,518 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:36:05,518 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:36:08,611 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:36:08,611 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:36:08,611 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:36:08,612 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:36:08,612 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:36:09,442 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:36:09,443 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:36:13,613 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:36:18,613 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:36:19,615 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:36:20,518 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:36:20,518 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:36:23,740 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:36:28,741 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:36:33,741 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:36:35,518 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:36:35,519 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:36:38,645 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:36:38,646 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:36:38,647 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:36:38,647 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:36:39,449 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:36:39,450 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:36:39,647 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:36:44,648 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:36:49,615 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:36:50,518 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:36:50,519 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:36:50,777 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:36:55,777 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:37:00,778 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:37:05,519 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:37:05,519 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:37:06,753 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:37:10,042 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:37:10,043 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:37:10,043 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:37:10,043 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:37:10,457 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:37:11,458 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:37:12,044 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:37:17,045 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:37:19,616 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:37:20,519 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:37:20,519 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:37:22,749 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:37:27,750 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:37:32,750 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:37:35,519 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:37:35,519 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:37:37,777 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:37:41,440 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:37:41,440 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:37:41,440 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:37:41,442 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:37:41,464 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:37:43,442 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:37:43,465 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:37:48,443 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:37:49,616 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:37:50,519 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:37:50,519 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:37:53,763 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:37:58,764 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:38:03,764 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:38:05,519 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:38:05,519 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:38:09,755 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:38:12,322 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:38:12,323 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:38:12,323 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:38:12,324 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:38:12,472 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:38:13,472 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:38:15,325 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:38:19,617 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:38:20,519 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:38:20,519 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:38:20,761 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:38:25,761 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:38:30,762 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:38:35,519 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:38:35,520 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:38:36,755 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:38:41,756 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:38:44,038 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:38:44,039 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:38:44,039 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:38:44,040 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:38:44,480 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:38:45,480 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:38:47,041 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:38:49,618 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:38:50,520 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:38:50,520 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:38:52,758 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:38:57,758 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:39:02,759 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:39:05,521 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:39:05,521 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:39:08,756 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:39:13,756 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:39:15,196 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:39:15,197 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:39:15,197 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:39:15,197 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:39:15,488 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:39:17,488 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:39:19,198 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:39:19,618 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:39:20,521 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:39:20,522 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:39:24,758 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:39:29,758 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:39:34,759 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:39:35,522 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:39:35,522 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:39:39,766 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:39:44,767 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:39:45,529 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:39:45,530 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:39:45,530 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:39:45,531 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:39:46,496 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:39:47,496 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:39:49,618 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:39:50,522 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:39:50,523 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:39:50,748 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:39:55,749 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:40:00,750 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:40:05,522 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:40:05,523 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:40:05,762 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:40:10,763 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:40:15,763 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:40:16,915 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:40:16,916 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:40:16,916 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:40:16,917 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:40:17,504 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:40:17,504 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:40:19,619 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:40:20,522 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:40:20,522 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:40:21,747 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:40:26,748 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:40:31,748 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:40:35,523 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:40:35,523 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:40:36,756 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:40:41,757 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:40:46,758 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:40:48,499 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:40:48,500 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:40:48,500 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:40:48,501 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:40:48,512 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:40:49,512 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:40:49,620 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:40:50,523 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:40:50,523 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:40:52,757 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:40:57,758 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:41:02,758 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:41:05,523 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:41:05,523 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:41:08,756 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:41:13,756 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:41:18,757 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:41:19,620 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:41:19,892 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:41:19,893 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:41:19,893 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:41:19,893 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:41:20,520 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:41:20,523 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:41:20,523 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:41:21,521 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:41:23,758 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:41:28,759 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:41:33,759 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:41:35,523 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:41:35,523 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:41:39,748 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:41:44,749 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:41:49,621 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:41:50,523 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:41:50,523 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:41:50,755 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:41:51,586 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:41:51,587 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:41:51,587 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:41:51,587 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:41:52,528 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:41:53,528 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:41:56,588 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:42:01,589 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:42:05,526 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:42:05,526 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:42:06,760 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:42:11,761 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:42:16,762 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:42:19,621 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:42:20,526 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:42:20,527 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:42:21,837 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:42:21,838 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:42:21,838 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:42:21,838 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:42:21,838 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:42:22,535 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:42:23,536 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:42:26,839 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:42:31,840 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:42:35,526 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:42:35,527 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:42:37,773 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:42:42,773 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:42:47,774 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:42:49,622 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:42:50,527 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:42:50,527 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:42:51,789 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:42:51,790 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:42:51,790 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:42:51,790 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:42:52,546 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:42:52,791 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:42:54,546 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:42:57,791 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:43:02,792 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:43:05,527 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:43:05,527 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:43:08,760 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:43:13,760 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:43:18,761 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:43:19,623 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:43:20,527 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:43:20,527 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:43:23,389 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:43:23,389 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:43:23,389 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:43:23,390 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:43:23,553 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:43:24,390 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:43:26,554 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:43:29,391 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:43:34,391 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:43:35,527 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:43:35,527 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:43:39,807 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:43:44,808 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:43:49,623 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:43:50,527 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:43:50,528 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:43:50,753 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:43:54,061 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:43:54,062 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:43:54,062 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:43:54,062 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:43:54,561 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:43:56,063 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:43:56,561 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:44:01,063 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:44:05,527 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:44:05,528 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:44:06,754 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:44:11,755 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:44:16,755 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:44:19,624 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:44:20,528 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:44:20,528 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:44:21,767 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:44:24,815 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:44:24,816 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:44:24,816 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:44:24,816 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:44:25,568 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:44:26,568 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:44:26,817 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:44:31,817 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:44:35,528 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:44:35,528 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:44:37,765 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:44:42,766 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:44:47,766 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:44:49,624 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:44:50,528 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:44:50,528 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:44:53,761 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:44:55,593 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:44:55,594 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:44:55,595 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:44:55,595 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:44:56,576 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:44:58,576 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:44:59,595 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:45:04,596 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:45:05,528 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:45:05,528 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:45:09,756 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:45:14,756 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:45:19,625 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:45:20,530 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:45:20,530 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:45:20,756 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:45:25,756 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:45:27,077 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:45:27,078 DEBUG   SenderThread:30284 [sender.py:send():369] send: history
2023-07-10 19:45:27,078 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:45:27,078 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:45:27,347 DEBUG   SenderThread:30284 [sender.py:send():369] send: exit
2023-07-10 19:45:27,347 INFO    SenderThread:30284 [sender.py:send_exit():574] handling exit code: 1
2023-07-10 19:45:27,347 INFO    SenderThread:30284 [sender.py:send_exit():576] handling runtime: 637
2023-07-10 19:45:27,347 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:45:27,347 INFO    SenderThread:30284 [sender.py:send_exit():582] send defer
2023-07-10 19:45:27,347 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:27,347 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 0
2023-07-10 19:45:27,347 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:27,348 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 0
2023-07-10 19:45:27,348 INFO    SenderThread:30284 [sender.py:transition_state():602] send defer: 1
2023-07-10 19:45:27,348 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:27,348 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 1
2023-07-10 19:45:27,348 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:27,348 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 1
2023-07-10 19:45:27,348 INFO    SenderThread:30284 [sender.py:transition_state():602] send defer: 2
2023-07-10 19:45:27,348 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:27,348 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 2
2023-07-10 19:45:27,348 INFO    HandlerThread:30284 [system_monitor.py:finish():190] Stopping system monitor
2023-07-10 19:45:27,348 DEBUG   SystemMonitor:30284 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-07-10 19:45:27,348 INFO    HandlerThread:30284 [interfaces.py:finish():202] Joined cpu monitor
2023-07-10 19:45:27,348 DEBUG   SystemMonitor:30284 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-07-10 19:45:27,348 INFO    HandlerThread:30284 [interfaces.py:finish():202] Joined disk monitor
2023-07-10 19:45:27,413 INFO    HandlerThread:30284 [interfaces.py:finish():202] Joined gpu monitor
2023-07-10 19:45:27,413 INFO    HandlerThread:30284 [interfaces.py:finish():202] Joined memory monitor
2023-07-10 19:45:27,413 INFO    HandlerThread:30284 [interfaces.py:finish():202] Joined network monitor
2023-07-10 19:45:27,413 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:27,413 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 2
2023-07-10 19:45:27,413 INFO    SenderThread:30284 [sender.py:transition_state():602] send defer: 3
2023-07-10 19:45:27,413 DEBUG   SenderThread:30284 [sender.py:send():369] send: stats
2023-07-10 19:45:27,413 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:27,414 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 3
2023-07-10 19:45:27,414 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:27,414 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 3
2023-07-10 19:45:27,414 INFO    SenderThread:30284 [sender.py:transition_state():602] send defer: 4
2023-07-10 19:45:27,414 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:27,414 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 4
2023-07-10 19:45:27,414 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:27,414 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 4
2023-07-10 19:45:27,414 INFO    SenderThread:30284 [sender.py:transition_state():602] send defer: 5
2023-07-10 19:45:27,414 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:27,414 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 5
2023-07-10 19:45:27,414 DEBUG   SenderThread:30284 [sender.py:send():369] send: summary
2023-07-10 19:45:27,415 INFO    SenderThread:30284 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:45:27,415 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:27,415 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 5
2023-07-10 19:45:27,415 INFO    SenderThread:30284 [sender.py:transition_state():602] send defer: 6
2023-07-10 19:45:27,415 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:27,415 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 6
2023-07-10 19:45:27,415 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:27,415 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 6
2023-07-10 19:45:27,415 INFO    SenderThread:30284 [sender.py:transition_state():602] send defer: 7
2023-07-10 19:45:27,415 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:45:27,415 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:27,415 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 7
2023-07-10 19:45:27,415 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:27,415 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 7
2023-07-10 19:45:27,583 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
2023-07-10 19:45:28,347 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: poll_exit
2023-07-10 19:45:28,584 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:45:30,584 INFO    Thread-12 :30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:45:31,688 INFO    SenderThread:30284 [sender.py:transition_state():602] send defer: 8
2023-07-10 19:45:31,688 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: poll_exit
2023-07-10 19:45:31,689 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:31,689 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 8
2023-07-10 19:45:31,689 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:31,689 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 8
2023-07-10 19:45:31,689 INFO    SenderThread:30284 [job_builder.py:build():232] Attempting to build job artifact
2023-07-10 19:45:31,689 INFO    SenderThread:30284 [job_builder.py:build():266] no source found
2023-07-10 19:45:31,689 INFO    SenderThread:30284 [sender.py:transition_state():602] send defer: 9
2023-07-10 19:45:31,689 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:31,689 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 9
2023-07-10 19:45:31,689 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:31,689 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 9
2023-07-10 19:45:31,689 INFO    SenderThread:30284 [dir_watcher.py:finish():359] shutting down directory watcher
2023-07-10 19:45:32,585 INFO    SenderThread:30284 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
2023-07-10 19:45:32,585 INFO    SenderThread:30284 [dir_watcher.py:finish():389] scan: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files
2023-07-10 19:45:32,586 INFO    SenderThread:30284 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-metadata.json wandb-metadata.json
2023-07-10 19:45:32,586 INFO    SenderThread:30284 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/config.yaml config.yaml
2023-07-10 19:45:32,586 INFO    SenderThread:30284 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/requirements.txt requirements.txt
2023-07-10 19:45:32,586 INFO    SenderThread:30284 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json wandb-summary.json
2023-07-10 19:45:32,586 INFO    SenderThread:30284 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/conda-environment.yaml conda-environment.yaml
2023-07-10 19:45:32,586 INFO    SenderThread:30284 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log output.log
2023-07-10 19:45:32,586 INFO    SenderThread:30284 [sender.py:transition_state():602] send defer: 10
2023-07-10 19:45:32,590 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:32,590 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 10
2023-07-10 19:45:32,592 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:32,593 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 10
2023-07-10 19:45:32,593 INFO    SenderThread:30284 [file_pusher.py:finish():159] shutting down file pusher
2023-07-10 19:45:33,042 ERROR   wandb-upload_0:30284 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/config.yaml?Expires=1689075932&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VWzKZ6oUIT%2BOR%2F6OASzkUeFp31Q91QEpS5BQry7dnlY5skCVbgjy1GgpBOLb%2Bb5wGCvmh%2BPfvr4kDWTzxhBybjcE3fiaNvY5FT0joY8QK8ng8meTh3ptRO7tC%2BwFDHXS2nrIG4B3cFDnu9TDsyufQXa%2FIjdvEXjJ1dpU4CWXJ3bmT3Cai3FBGnNvDLyb0wzqOSXkiypsVPK7fRoi7mQdAI%2B0Lt3xM9pimhoTjk9aDcSsVy0xjzCE%2FQlyRtNZ0jHrgZggPgBvOMYiagS6uiyZ%2FvoPZOBx2j2di5M%2FvYmurGFupopsqczxFejRnvZkCRm3GAAnyZmMhvL0aAqPPy0lsQ%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/config.yaml?Expires=1689075932&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VWzKZ6oUIT%2BOR%2F6OASzkUeFp31Q91QEpS5BQry7dnlY5skCVbgjy1GgpBOLb%2Bb5wGCvmh%2BPfvr4kDWTzxhBybjcE3fiaNvY5FT0joY8QK8ng8meTh3ptRO7tC%2BwFDHXS2nrIG4B3cFDnu9TDsyufQXa%2FIjdvEXjJ1dpU4CWXJ3bmT3Cai3FBGnNvDLyb0wzqOSXkiypsVPK7fRoi7mQdAI%2B0Lt3xM9pimhoTjk9aDcSsVy0xjzCE%2FQlyRtNZ0jHrgZggPgBvOMYiagS6uiyZ%2FvoPZOBx2j2di5M%2FvYmurGFupopsqczxFejRnvZkCRm3GAAnyZmMhvL0aAqPPy0lsQ%3D%3D
2023-07-10 19:45:33,042 ERROR   wandb-upload_0:30284 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '525'}
2023-07-10 19:45:33,042 ERROR   wandb-upload_0:30284 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/config.yaml</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:45:33,349 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: keepalive
2023-07-10 19:45:34,811 ERROR   wandb-upload_4:30284 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/output.log?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rdMhh77CpvBlKaEQDEYIXXTGVXQjxW%2BixtklVMNUhmiXWtvTrho%2BRG2Uz6PktRbkuw8tuUNcXJqNm68uEbPaP1AqT7p4SIc3PfmM6hcvjbIUUMzD9gWYYiWbd8Ibi6RE4lKpbczQDpPbkn13rrgiKLPy42YrS4NEx4HG7doIH2o%2Bmk%2F1tUfqywTK6ZtuTyod1zBjGAmydJzP0B0%2FgFCg7YJlq14u9hbhfCZGVcVWX7%2B%2FmDV9J%2BVCoq5QofQxUEmGVQPsJ45cRuvzuY9Mws%2F%2Bb1la9%2BxaJ%2FHLTdickYiLDHwb8ywIdCSko%2F4JSxF%2BtZrQ9bULklmrlx3HMAsgovfLEw%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/output.log?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rdMhh77CpvBlKaEQDEYIXXTGVXQjxW%2BixtklVMNUhmiXWtvTrho%2BRG2Uz6PktRbkuw8tuUNcXJqNm68uEbPaP1AqT7p4SIc3PfmM6hcvjbIUUMzD9gWYYiWbd8Ibi6RE4lKpbczQDpPbkn13rrgiKLPy42YrS4NEx4HG7doIH2o%2Bmk%2F1tUfqywTK6ZtuTyod1zBjGAmydJzP0B0%2FgFCg7YJlq14u9hbhfCZGVcVWX7%2B%2FmDV9J%2BVCoq5QofQxUEmGVQPsJ45cRuvzuY9Mws%2F%2Bb1la9%2BxaJ%2FHLTdickYiLDHwb8ywIdCSko%2F4JSxF%2BtZrQ9bULklmrlx3HMAsgovfLEw%3D%3D
2023-07-10 19:45:34,811 ERROR   wandb-upload_4:30284 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '28322'}
2023-07-10 19:45:34,811 ERROR   wandb-upload_4:30284 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/output.log</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:45:34,873 ERROR   wandb-upload_3:30284 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/conda-environment.yaml?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=SXYuE40xwr7BnoqoOytgcecmYl9kDCRYGCbDThOr6AT%2B7pmJmdXbRwSzao2lXCCUF%2F7eTRNLf2jrSJP9TbFvDkT4mqeWn%2F16I4AOEM0Kr4YBzUkfgVMb1c%2BJUj4fCIm4UFIPaER7GjDbtfJbkVyC1q7SKyhtzQhiMPpe%2F8p9Cdf4pI0DX8YHwWDAv6%2F40kXYEzpAsZQwTWFNUOdF4%2FHhWiKc0MD5BPuVCuuipBkX0wNuS4BiQjdyJ92SV9JdflfVU4khvl3JVXIjSwkVmH0ZcQTTq1RnoneEk%2FKYt7MkLoJ3RLDcoQ7%2Fymy2J4H9dhWiSxwZ7T6C%2F5HWSDiKTb4vWQ%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/conda-environment.yaml?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=SXYuE40xwr7BnoqoOytgcecmYl9kDCRYGCbDThOr6AT%2B7pmJmdXbRwSzao2lXCCUF%2F7eTRNLf2jrSJP9TbFvDkT4mqeWn%2F16I4AOEM0Kr4YBzUkfgVMb1c%2BJUj4fCIm4UFIPaER7GjDbtfJbkVyC1q7SKyhtzQhiMPpe%2F8p9Cdf4pI0DX8YHwWDAv6%2F40kXYEzpAsZQwTWFNUOdF4%2FHhWiKc0MD5BPuVCuuipBkX0wNuS4BiQjdyJ92SV9JdflfVU4khvl3JVXIjSwkVmH0ZcQTTq1RnoneEk%2FKYt7MkLoJ3RLDcoQ7%2Fymy2J4H9dhWiSxwZ7T6C%2F5HWSDiKTb4vWQ%3D%3D
2023-07-10 19:45:34,873 ERROR   wandb-upload_3:30284 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1925'}
2023-07-10 19:45:34,873 ERROR   wandb-upload_3:30284 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/conda-environment.yaml</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:45:34,875 ERROR   wandb-upload_1:30284 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/requirements.txt?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LDcgNb82mZBOVkiR4DT0kazi%2FRbLnBRjCS%2F4JuhSZowJ3hdgCvy7L72AzvRQqKS8K1IMrB5eUox30sOaRJWtfN1GrgSSshM%2Fy5X8WUjy0TXOK0U2LrnZQ5TmuENuHtb5iXO3ZW3EVFy46k4W5D6deCLdGfbn%2BrtYf8nO3cDEON0fCoeR%2BLmXqPQ1ABmwud7QCYZXPNu3RuNyx%2BJx6cg1%2FveeW0AuE9XOgQEkg3LGczLftSHYaiI4LJO%2FEwHbWl7gMupTgVsmUaEz4dV1QPmJfS8lnR7p4nGfl8AVcLf2N%2Bm9ldi0YG8BjL7NlxAcBy54asYaKdgcvcQ55IyLgHXf1g%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/requirements.txt?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LDcgNb82mZBOVkiR4DT0kazi%2FRbLnBRjCS%2F4JuhSZowJ3hdgCvy7L72AzvRQqKS8K1IMrB5eUox30sOaRJWtfN1GrgSSshM%2Fy5X8WUjy0TXOK0U2LrnZQ5TmuENuHtb5iXO3ZW3EVFy46k4W5D6deCLdGfbn%2BrtYf8nO3cDEON0fCoeR%2BLmXqPQ1ABmwud7QCYZXPNu3RuNyx%2BJx6cg1%2FveeW0AuE9XOgQEkg3LGczLftSHYaiI4LJO%2FEwHbWl7gMupTgVsmUaEz4dV1QPmJfS8lnR7p4nGfl8AVcLf2N%2Bm9ldi0YG8BjL7NlxAcBy54asYaKdgcvcQ55IyLgHXf1g%3D%3D
2023-07-10 19:45:34,876 ERROR   wandb-upload_1:30284 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '926'}
2023-07-10 19:45:34,876 ERROR   wandb-upload_1:30284 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/requirements.txt</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:45:34,881 ERROR   wandb-upload_2:30284 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/wandb-summary.json?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AtemioCn1NE%2FlAk6MPx4mT%2BGDAdpLt7GbWNu6oEUd8ZikKEYq4k9ZwMjRWRrI0UYJXzShULVdSB87Rz%2FbdaDwDDijKcIMt5H9CsFOusIeGWUzko4ByjiVtEyn6d%2B%2FSvHdxfX0%2FgAaeHI02UpNMj0HbOJktvhcJDKSwXpT%2Fafhh4wXrNm8E7k54GzENsZdubMbTy9SgsmuPUbA1cRyz7nF6m%2Bny1vieXThDicLXjLEijePHor0Pwn6Qaz7vUzHBIOGrHUIh%2F1LHADWs%2Bg3%2Bzz5a9fM3bakqthicHvnH0D5GRP85aSYALuOTu4zuh6vEbIODVnMFTnNyIc%2BJLZz%2FyP3w%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/wandb-summary.json?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AtemioCn1NE%2FlAk6MPx4mT%2BGDAdpLt7GbWNu6oEUd8ZikKEYq4k9ZwMjRWRrI0UYJXzShULVdSB87Rz%2FbdaDwDDijKcIMt5H9CsFOusIeGWUzko4ByjiVtEyn6d%2B%2FSvHdxfX0%2FgAaeHI02UpNMj0HbOJktvhcJDKSwXpT%2Fafhh4wXrNm8E7k54GzENsZdubMbTy9SgsmuPUbA1cRyz7nF6m%2Bny1vieXThDicLXjLEijePHor0Pwn6Qaz7vUzHBIOGrHUIh%2F1LHADWs%2Bg3%2Bzz5a9fM3bakqthicHvnH0D5GRP85aSYALuOTu4zuh6vEbIODVnMFTnNyIc%2BJLZz%2FyP3w%3D%3D
2023-07-10 19:45:34,881 ERROR   wandb-upload_2:30284 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '166'}
2023-07-10 19:45:34,881 ERROR   wandb-upload_2:30284 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/wandb-summary.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:45:35,044 ERROR   wandb-upload_0:30284 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/config.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/config.yaml?Expires=1689075932&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VWzKZ6oUIT%2BOR%2F6OASzkUeFp31Q91QEpS5BQry7dnlY5skCVbgjy1GgpBOLb%2Bb5wGCvmh%2BPfvr4kDWTzxhBybjcE3fiaNvY5FT0joY8QK8ng8meTh3ptRO7tC%2BwFDHXS2nrIG4B3cFDnu9TDsyufQXa%2FIjdvEXjJ1dpU4CWXJ3bmT3Cai3FBGnNvDLyb0wzqOSXkiypsVPK7fRoi7mQdAI%2B0Lt3xM9pimhoTjk9aDcSsVy0xjzCE%2FQlyRtNZ0jHrgZggPgBvOMYiagS6uiyZ%2FvoPZOBx2j2di5M%2FvYmurGFupopsqczxFejRnvZkCRm3GAAnyZmMhvL0aAqPPy0lsQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:45:36,498 ERROR   wandb-upload_4:30284 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/output.log?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rdMhh77CpvBlKaEQDEYIXXTGVXQjxW%2BixtklVMNUhmiXWtvTrho%2BRG2Uz6PktRbkuw8tuUNcXJqNm68uEbPaP1AqT7p4SIc3PfmM6hcvjbIUUMzD9gWYYiWbd8Ibi6RE4lKpbczQDpPbkn13rrgiKLPy42YrS4NEx4HG7doIH2o%2Bmk%2F1tUfqywTK6ZtuTyod1zBjGAmydJzP0B0%2FgFCg7YJlq14u9hbhfCZGVcVWX7%2B%2FmDV9J%2BVCoq5QofQxUEmGVQPsJ45cRuvzuY9Mws%2F%2Bb1la9%2BxaJ%2FHLTdickYiLDHwb8ywIdCSko%2F4JSxF%2BtZrQ9bULklmrlx3HMAsgovfLEw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:45:36,499 ERROR   wandb-upload_3:30284 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/conda-environment.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/conda-environment.yaml?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=SXYuE40xwr7BnoqoOytgcecmYl9kDCRYGCbDThOr6AT%2B7pmJmdXbRwSzao2lXCCUF%2F7eTRNLf2jrSJP9TbFvDkT4mqeWn%2F16I4AOEM0Kr4YBzUkfgVMb1c%2BJUj4fCIm4UFIPaER7GjDbtfJbkVyC1q7SKyhtzQhiMPpe%2F8p9Cdf4pI0DX8YHwWDAv6%2F40kXYEzpAsZQwTWFNUOdF4%2FHhWiKc0MD5BPuVCuuipBkX0wNuS4BiQjdyJ92SV9JdflfVU4khvl3JVXIjSwkVmH0ZcQTTq1RnoneEk%2FKYt7MkLoJ3RLDcoQ7%2Fymy2J4H9dhWiSxwZ7T6C%2F5HWSDiKTb4vWQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:45:36,499 ERROR   wandb-upload_1:30284 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/requirements.txt
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/requirements.txt?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LDcgNb82mZBOVkiR4DT0kazi%2FRbLnBRjCS%2F4JuhSZowJ3hdgCvy7L72AzvRQqKS8K1IMrB5eUox30sOaRJWtfN1GrgSSshM%2Fy5X8WUjy0TXOK0U2LrnZQ5TmuENuHtb5iXO3ZW3EVFy46k4W5D6deCLdGfbn%2BrtYf8nO3cDEON0fCoeR%2BLmXqPQ1ABmwud7QCYZXPNu3RuNyx%2BJx6cg1%2FveeW0AuE9XOgQEkg3LGczLftSHYaiI4LJO%2FEwHbWl7gMupTgVsmUaEz4dV1QPmJfS8lnR7p4nGfl8AVcLf2N%2Bm9ldi0YG8BjL7NlxAcBy54asYaKdgcvcQ55IyLgHXf1g%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:45:36,500 ERROR   wandb-upload_2:30284 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/wandb-summary.json?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AtemioCn1NE%2FlAk6MPx4mT%2BGDAdpLt7GbWNu6oEUd8ZikKEYq4k9ZwMjRWRrI0UYJXzShULVdSB87Rz%2FbdaDwDDijKcIMt5H9CsFOusIeGWUzko4ByjiVtEyn6d%2B%2FSvHdxfX0%2FgAaeHI02UpNMj0HbOJktvhcJDKSwXpT%2Fafhh4wXrNm8E7k54GzENsZdubMbTy9SgsmuPUbA1cRyz7nF6m%2Bny1vieXThDicLXjLEijePHor0Pwn6Qaz7vUzHBIOGrHUIh%2F1LHADWs%2Bg3%2Bzz5a9fM3bakqthicHvnH0D5GRP85aSYALuOTu4zuh6vEbIODVnMFTnNyIc%2BJLZz%2FyP3w%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:45:36,500 ERROR   Thread-11 :30284 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/config.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/config.yaml?Expires=1689075932&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VWzKZ6oUIT%2BOR%2F6OASzkUeFp31Q91QEpS5BQry7dnlY5skCVbgjy1GgpBOLb%2Bb5wGCvmh%2BPfvr4kDWTzxhBybjcE3fiaNvY5FT0joY8QK8ng8meTh3ptRO7tC%2BwFDHXS2nrIG4B3cFDnu9TDsyufQXa%2FIjdvEXjJ1dpU4CWXJ3bmT3Cai3FBGnNvDLyb0wzqOSXkiypsVPK7fRoi7mQdAI%2B0Lt3xM9pimhoTjk9aDcSsVy0xjzCE%2FQlyRtNZ0jHrgZggPgBvOMYiagS6uiyZ%2FvoPZOBx2j2di5M%2FvYmurGFupopsqczxFejRnvZkCRm3GAAnyZmMhvL0aAqPPy0lsQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:45:37,332 ERROR   Thread-11 :30284 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/output.log
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/output.log?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rdMhh77CpvBlKaEQDEYIXXTGVXQjxW%2BixtklVMNUhmiXWtvTrho%2BRG2Uz6PktRbkuw8tuUNcXJqNm68uEbPaP1AqT7p4SIc3PfmM6hcvjbIUUMzD9gWYYiWbd8Ibi6RE4lKpbczQDpPbkn13rrgiKLPy42YrS4NEx4HG7doIH2o%2Bmk%2F1tUfqywTK6ZtuTyod1zBjGAmydJzP0B0%2FgFCg7YJlq14u9hbhfCZGVcVWX7%2B%2FmDV9J%2BVCoq5QofQxUEmGVQPsJ45cRuvzuY9Mws%2F%2Bb1la9%2BxaJ%2FHLTdickYiLDHwb8ywIdCSko%2F4JSxF%2BtZrQ9bULklmrlx3HMAsgovfLEw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:45:37,333 ERROR   Thread-11 :30284 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/requirements.txt
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/requirements.txt?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LDcgNb82mZBOVkiR4DT0kazi%2FRbLnBRjCS%2F4JuhSZowJ3hdgCvy7L72AzvRQqKS8K1IMrB5eUox30sOaRJWtfN1GrgSSshM%2Fy5X8WUjy0TXOK0U2LrnZQ5TmuENuHtb5iXO3ZW3EVFy46k4W5D6deCLdGfbn%2BrtYf8nO3cDEON0fCoeR%2BLmXqPQ1ABmwud7QCYZXPNu3RuNyx%2BJx6cg1%2FveeW0AuE9XOgQEkg3LGczLftSHYaiI4LJO%2FEwHbWl7gMupTgVsmUaEz4dV1QPmJfS8lnR7p4nGfl8AVcLf2N%2Bm9ldi0YG8BjL7NlxAcBy54asYaKdgcvcQ55IyLgHXf1g%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:45:37,333 ERROR   Thread-11 :30284 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/wandb-summary.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/wandb-summary.json?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AtemioCn1NE%2FlAk6MPx4mT%2BGDAdpLt7GbWNu6oEUd8ZikKEYq4k9ZwMjRWRrI0UYJXzShULVdSB87Rz%2FbdaDwDDijKcIMt5H9CsFOusIeGWUzko4ByjiVtEyn6d%2B%2FSvHdxfX0%2FgAaeHI02UpNMj0HbOJktvhcJDKSwXpT%2Fafhh4wXrNm8E7k54GzENsZdubMbTy9SgsmuPUbA1cRyz7nF6m%2Bny1vieXThDicLXjLEijePHor0Pwn6Qaz7vUzHBIOGrHUIh%2F1LHADWs%2Bg3%2Bzz5a9fM3bakqthicHvnH0D5GRP85aSYALuOTu4zuh6vEbIODVnMFTnNyIc%2BJLZz%2FyP3w%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:45:37,333 ERROR   Thread-11 :30284 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/files/conda-environment.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/g7dnlenp/conda-environment.yaml?Expires=1689075934&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=SXYuE40xwr7BnoqoOytgcecmYl9kDCRYGCbDThOr6AT%2B7pmJmdXbRwSzao2lXCCUF%2F7eTRNLf2jrSJP9TbFvDkT4mqeWn%2F16I4AOEM0Kr4YBzUkfgVMb1c%2BJUj4fCIm4UFIPaER7GjDbtfJbkVyC1q7SKyhtzQhiMPpe%2F8p9Cdf4pI0DX8YHwWDAv6%2F40kXYEzpAsZQwTWFNUOdF4%2FHhWiKc0MD5BPuVCuuipBkX0wNuS4BiQjdyJ92SV9JdflfVU4khvl3JVXIjSwkVmH0ZcQTTq1RnoneEk%2FKYt7MkLoJ3RLDcoQ7%2Fymy2J4H9dhWiSxwZ7T6C%2F5HWSDiKTb4vWQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:45:37,534 INFO    Thread-11 :30284 [sender.py:transition_state():602] send defer: 11
2023-07-10 19:45:37,534 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:37,534 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 11
2023-07-10 19:45:37,534 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:37,534 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 11
2023-07-10 19:45:37,534 INFO    SenderThread:30284 [file_pusher.py:join():164] waiting for file pusher
2023-07-10 19:45:37,534 INFO    SenderThread:30284 [sender.py:transition_state():602] send defer: 12
2023-07-10 19:45:37,535 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:37,535 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 12
2023-07-10 19:45:37,535 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:45:37,535 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:37,535 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 12
2023-07-10 19:45:38,093 INFO    SenderThread:30284 [sender.py:transition_state():602] send defer: 13
2023-07-10 19:45:38,093 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:38,093 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 13
2023-07-10 19:45:38,093 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:38,093 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 13
2023-07-10 19:45:38,093 INFO    SenderThread:30284 [sender.py:transition_state():602] send defer: 14
2023-07-10 19:45:38,093 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:45:38,093 INFO    HandlerThread:30284 [handler.py:handle_request_defer():170] handle defer: 14
2023-07-10 19:45:38,094 DEBUG   SenderThread:30284 [sender.py:send():369] send: final
2023-07-10 19:45:38,094 DEBUG   SenderThread:30284 [sender.py:send():369] send: footer
2023-07-10 19:45:38,094 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: defer
2023-07-10 19:45:38,094 INFO    SenderThread:30284 [sender.py:send_request_defer():598] handle sender defer: 14
2023-07-10 19:45:38,094 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: poll_exit
2023-07-10 19:45:38,094 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: server_info
2023-07-10 19:45:38,095 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: get_summary
2023-07-10 19:45:38,095 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: poll_exit
2023-07-10 19:45:38,095 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: sampled_history
2023-07-10 19:45:38,095 DEBUG   SenderThread:30284 [sender.py:send_request():396] send_request: server_info
2023-07-10 19:45:38,597 INFO    MainThread:30284 [wandb_run.py:_footer_history_summary_info():3467] rendering history
2023-07-10 19:45:38,597 INFO    MainThread:30284 [wandb_run.py:_footer_history_summary_info():3499] rendering summary
2023-07-10 19:45:38,597 INFO    MainThread:30284 [wandb_run.py:_footer_sync_info():3426] logging synced files
2023-07-10 19:45:38,597 DEBUG   HandlerThread:30284 [handler.py:handle_request():144] handle_request: shutdown
2023-07-10 19:45:38,597 INFO    HandlerThread:30284 [handler.py:finish():854] shutting down handler
2023-07-10 19:45:39,094 INFO    WriterThread:30284 [datastore.py:close():298] close: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_193448-g7dnlenp/run-g7dnlenp.wandb
2023-07-10 19:45:39,597 INFO    SenderThread:30284 [sender.py:finish():1526] shutting down sender
2023-07-10 19:45:39,597 INFO    SenderThread:30284 [file_pusher.py:finish():159] shutting down file pusher
2023-07-10 19:45:39,597 INFO    SenderThread:30284 [file_pusher.py:join():164] waiting for file pusher
