2023-07-10 17:57:58,597 INFO    StreamThr :10535 [internal.py:wandb_internal():86] W&B internal server running at pid: 10535, started at: 2023-07-10 17:57:58.596791
2023-07-10 17:57:58,600 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status
2023-07-10 17:57:58,602 INFO    WriterThread:10535 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175758-lu4lkhgg/run-lu4lkhgg.wandb
2023-07-10 17:57:58,603 DEBUG   SenderThread:10535 [sender.py:send():369] send: header
2023-07-10 17:57:58,603 DEBUG   SenderThread:10535 [sender.py:send():369] send: run
2023-07-10 17:57:59,545 INFO    SenderThread:10535 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175758-lu4lkhgg/files
2023-07-10 17:57:59,545 INFO    SenderThread:10535 [sender.py:_start_run_threads():1100] run started: lu4lkhgg with start time 1688983078.596248
2023-07-10 17:57:59,545 DEBUG   SenderThread:10535 [sender.py:send_request():396] send_request: summary_record
2023-07-10 17:57:59,545 INFO    SenderThread:10535 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 17:57:59,551 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 17:57:59,551 DEBUG   SenderThread:10535 [sender.py:send_request():396] send_request: check_version
2023-07-10 17:57:59,733 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 17:57:59,737 DEBUG   HandlerThread:10535 [system_info.py:__init__():31] System info init
2023-07-10 17:57:59,737 DEBUG   HandlerThread:10535 [system_info.py:__init__():46] System info init done
2023-07-10 17:57:59,737 INFO    HandlerThread:10535 [system_monitor.py:start():181] Starting system monitor
2023-07-10 17:57:59,737 INFO    HandlerThread:10535 [system_monitor.py:probe():201] Collecting system info
2023-07-10 17:57:59,738 INFO    SystemMonitor:10535 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 17:57:59,739 INFO    SystemMonitor:10535 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 17:57:59,740 INFO    SystemMonitor:10535 [interfaces.py:start():190] Started disk monitoring
2023-07-10 17:57:59,742 INFO    SystemMonitor:10535 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 17:57:59,743 INFO    SystemMonitor:10535 [interfaces.py:start():190] Started memory monitoring
2023-07-10 17:57:59,743 INFO    SystemMonitor:10535 [interfaces.py:start():190] Started network monitoring
2023-07-10 17:57:59,753 DEBUG   HandlerThread:10535 [system_info.py:probe():195] Probing system
2023-07-10 17:57:59,756 DEBUG   HandlerThread:10535 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 17:57:59,756 DEBUG   HandlerThread:10535 [system_info.py:probe():240] Probing system done
2023-07-10 17:57:59,756 DEBUG   HandlerThread:10535 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T09:57:59.753477', 'startedAt': '2023-07-10T09:57:58.588355', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3858.0997083333336, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5102.599, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5097.946, 'min': 800.0, 'max': 5100.0}, {'current': 5107.327, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5099.987, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5102.635, 'min': 800.0, 'max': 5200.0}, {'current': 5101.415, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5097.897, 'min': 800.0, 'max': 5100.0}, {'current': 5099.933, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 3700.841, 'min': 800.0, 'max': 4100.0}, {'current': 3699.781, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.017681121826171875}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-10 17:57:59,756 INFO    HandlerThread:10535 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 17:57:59,756 INFO    HandlerThread:10535 [system_monitor.py:probe():214] Publishing system info
2023-07-10 17:57:59,756 DEBUG   HandlerThread:10535 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 17:57:59,757 DEBUG   HandlerThread:10535 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 17:57:59,757 DEBUG   HandlerThread:10535 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 17:58:00,514 DEBUG   HandlerThread:10535 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 17:58:00,517 INFO    HandlerThread:10535 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 17:58:00,520 DEBUG   SenderThread:10535 [sender.py:send():369] send: files
2023-07-10 17:58:00,520 INFO    SenderThread:10535 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 17:58:00,526 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 17:58:00,527 DEBUG   SenderThread:10535 [sender.py:send_request():396] send_request: stop_status
2023-07-10 17:58:00,547 INFO    Thread-17 :10535 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175758-lu4lkhgg/files/conda-environment.yaml
2023-07-10 17:58:00,547 INFO    Thread-17 :10535 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175758-lu4lkhgg/files/wandb-summary.json
2023-07-10 17:58:00,547 INFO    Thread-17 :10535 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175758-lu4lkhgg/files/wandb-metadata.json
2023-07-10 17:58:00,547 INFO    Thread-17 :10535 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175758-lu4lkhgg/files/requirements.txt
2023-07-10 17:58:01,022 ERROR   wandb-upload_0:10535 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/lu4lkhgg/wandb-metadata.json?Expires=1689069480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bg8Ac6u3cu80r2q2VuFoPRd0w4qQlsPiZGlmcW7rBprWW9aP0lj%2FJb8Dp1z%2F8R7isPYbS5DVIVBwhTyVKZjAOQOBbYaBQ%2B4zErSPT5owEVT7otRCDTmrHaW40G9RY2U8vHnVKpfdEXMOdElaFBbcwPAZrgrgXCy9nDbQCGMOwC1URGnlroIVrEKMqVFz0DMJx8awFPEXz5G2IpTTO0ZRpt8PEbBxLfqneT%2B8VuDiEuTUfmpPI7aDsMw5rG1VfxNneSeSYg%2FYMhu5hl5co989xgsA9d4uBvOVnNtdLbakw1ouOFQcz8u7w9LC7P56106%2Fyx46p2XauELFa44UXtJo5Q%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/lu4lkhgg/wandb-metadata.json?Expires=1689069480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bg8Ac6u3cu80r2q2VuFoPRd0w4qQlsPiZGlmcW7rBprWW9aP0lj%2FJb8Dp1z%2F8R7isPYbS5DVIVBwhTyVKZjAOQOBbYaBQ%2B4zErSPT5owEVT7otRCDTmrHaW40G9RY2U8vHnVKpfdEXMOdElaFBbcwPAZrgrgXCy9nDbQCGMOwC1URGnlroIVrEKMqVFz0DMJx8awFPEXz5G2IpTTO0ZRpt8PEbBxLfqneT%2B8VuDiEuTUfmpPI7aDsMw5rG1VfxNneSeSYg%2FYMhu5hl5co989xgsA9d4uBvOVnNtdLbakw1ouOFQcz8u7w9LC7P56106%2Fyx46p2XauELFa44UXtJo5Q%3D%3D
2023-07-10 17:58:01,023 ERROR   wandb-upload_0:10535 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3626'}
2023-07-10 17:58:01,023 ERROR   wandb-upload_0:10535 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/lu4lkhgg/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 17:58:01,102 DEBUG   SenderThread:10535 [sender.py:send():369] send: telemetry
2023-07-10 17:58:01,545 INFO    Thread-17 :10535 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175758-lu4lkhgg/files/output.log
2023-07-10 17:58:01,551 ERROR   wandb-upload_0:10535 [upload_job.py:push():136] Failed to upload file: /tmp/tmpug0msgokwandb/gvniqy5o-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/lu4lkhgg/wandb-metadata.json?Expires=1689069480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bg8Ac6u3cu80r2q2VuFoPRd0w4qQlsPiZGlmcW7rBprWW9aP0lj%2FJb8Dp1z%2F8R7isPYbS5DVIVBwhTyVKZjAOQOBbYaBQ%2B4zErSPT5owEVT7otRCDTmrHaW40G9RY2U8vHnVKpfdEXMOdElaFBbcwPAZrgrgXCy9nDbQCGMOwC1URGnlroIVrEKMqVFz0DMJx8awFPEXz5G2IpTTO0ZRpt8PEbBxLfqneT%2B8VuDiEuTUfmpPI7aDsMw5rG1VfxNneSeSYg%2FYMhu5hl5co989xgsA9d4uBvOVnNtdLbakw1ouOFQcz8u7w9LC7P56106%2Fyx46p2XauELFa44UXtJo5Q%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 17:58:01,761 ERROR   Thread-16 :10535 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpug0msgokwandb/gvniqy5o-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/lu4lkhgg/wandb-metadata.json?Expires=1689069480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bg8Ac6u3cu80r2q2VuFoPRd0w4qQlsPiZGlmcW7rBprWW9aP0lj%2FJb8Dp1z%2F8R7isPYbS5DVIVBwhTyVKZjAOQOBbYaBQ%2B4zErSPT5owEVT7otRCDTmrHaW40G9RY2U8vHnVKpfdEXMOdElaFBbcwPAZrgrgXCy9nDbQCGMOwC1URGnlroIVrEKMqVFz0DMJx8awFPEXz5G2IpTTO0ZRpt8PEbBxLfqneT%2B8VuDiEuTUfmpPI7aDsMw5rG1VfxNneSeSYg%2FYMhu5hl5co989xgsA9d4uBvOVnNtdLbakw1ouOFQcz8u7w9LC7P56106%2Fyx46p2XauELFa44UXtJo5Q%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 17:58:03,546 INFO    Thread-17 :10535 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175758-lu4lkhgg/files/output.log
2023-07-10 17:58:03,615 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:58:05,547 INFO    Thread-17 :10535 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175758-lu4lkhgg/files/output.log
2023-07-10 17:58:08,796 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:58:10,520 DEBUG   SenderThread:10535 [sender.py:send():369] send: telemetry
2023-07-10 17:58:11,549 INFO    Thread-17 :10535 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175758-lu4lkhgg/files/output.log
2023-07-10 17:58:14,316 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:58:15,525 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 17:58:15,526 DEBUG   SenderThread:10535 [sender.py:send_request():396] send_request: stop_status
2023-07-10 17:58:15,550 INFO    Thread-17 :10535 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175758-lu4lkhgg/files/output.log
2023-07-10 17:58:19,757 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:58:24,758 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:58:29,764 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:58:30,526 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 17:58:30,526 DEBUG   SenderThread:10535 [sender.py:send_request():396] send_request: stop_status
2023-07-10 17:58:30,555 INFO    Thread-17 :10535 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175758-lu4lkhgg/files/config.yaml
2023-07-10 17:58:35,753 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:58:40,754 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:58:45,526 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 17:58:45,527 DEBUG   SenderThread:10535 [sender.py:send_request():396] send_request: stop_status
2023-07-10 17:58:46,748 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:58:51,749 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:58:56,750 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:58:59,744 DEBUG   SystemMonitor:10535 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-10 17:58:59,746 DEBUG   SenderThread:10535 [sender.py:send():369] send: stats
2023-07-10 17:59:00,526 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 17:59:00,527 DEBUG   SenderThread:10535 [sender.py:send_request():396] send_request: stop_status
2023-07-10 17:59:02,747 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:59:07,748 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:59:12,748 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:59:15,526 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 17:59:15,527 DEBUG   SenderThread:10535 [sender.py:send_request():396] send_request: stop_status
2023-07-10 17:59:17,758 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:59:22,758 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:59:27,759 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:59:29,747 DEBUG   SenderThread:10535 [sender.py:send():369] send: stats
2023-07-10 17:59:30,526 DEBUG   HandlerThread:10535 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 17:59:30,527 DEBUG   SenderThread:10535 [sender.py:send_request():396] send_request: stop_status
