2023-07-10 19:20:52,244 INFO    StreamThr :28768 [internal.py:wandb_internal():86] W&B internal server running at pid: 28768, started at: 2023-07-10 19:20:52.244599
2023-07-10 19:20:52,246 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status
2023-07-10 19:20:52,246 INFO    WriterThread:28768 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/run-8ni8xi78.wandb
2023-07-10 19:20:52,247 DEBUG   SenderThread:28768 [sender.py:send():369] send: header
2023-07-10 19:20:52,247 DEBUG   SenderThread:28768 [sender.py:send():369] send: run
2023-07-10 19:20:53,129 INFO    SenderThread:28768 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files
2023-07-10 19:20:53,129 INFO    SenderThread:28768 [sender.py:_start_run_threads():1100] run started: 8ni8xi78 with start time 1688988052.244367
2023-07-10 19:20:53,129 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:20:53,129 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:20:53,129 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 19:20:53,129 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: check_version
2023-07-10 19:20:53,308 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 19:20:53,312 DEBUG   HandlerThread:28768 [system_info.py:__init__():31] System info init
2023-07-10 19:20:53,312 DEBUG   HandlerThread:28768 [system_info.py:__init__():46] System info init done
2023-07-10 19:20:53,312 INFO    HandlerThread:28768 [system_monitor.py:start():181] Starting system monitor
2023-07-10 19:20:53,312 INFO    SystemMonitor:28768 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 19:20:53,313 INFO    HandlerThread:28768 [system_monitor.py:probe():201] Collecting system info
2023-07-10 19:20:53,313 INFO    SystemMonitor:28768 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 19:20:53,313 INFO    SystemMonitor:28768 [interfaces.py:start():190] Started disk monitoring
2023-07-10 19:20:53,314 INFO    SystemMonitor:28768 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 19:20:53,314 INFO    SystemMonitor:28768 [interfaces.py:start():190] Started memory monitoring
2023-07-10 19:20:53,314 INFO    SystemMonitor:28768 [interfaces.py:start():190] Started network monitoring
2023-07-10 19:20:53,328 DEBUG   HandlerThread:28768 [system_info.py:probe():195] Probing system
2023-07-10 19:20:53,331 DEBUG   HandlerThread:28768 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 19:20:53,331 DEBUG   HandlerThread:28768 [system_info.py:probe():240] Probing system done
2023-07-10 19:20:53,331 DEBUG   HandlerThread:28768 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T11:20:53.328706', 'startedAt': '2023-07-10T11:20:52.240361', 'docker': None, 'cuda': None, 'args': ('--phase', 'train', '--gpu_ids', '1'), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3489.206041666667, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 4736.287, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5099.917, 'min': 800.0, 'max': 5100.0}, {'current': 5100.114, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5018.922, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5161.09, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5075.599, 'min': 800.0, 'max': 5200.0}, {'current': 4324.25, 'min': 800.0, 'max': 5200.0}, {'current': 5041.386, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 3683.38, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.01821136474609375}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-10 19:20:53,331 INFO    HandlerThread:28768 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 19:20:53,331 INFO    HandlerThread:28768 [system_monitor.py:probe():214] Publishing system info
2023-07-10 19:20:53,331 DEBUG   HandlerThread:28768 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 19:20:53,331 DEBUG   HandlerThread:28768 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 19:20:53,331 DEBUG   HandlerThread:28768 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 19:20:54,130 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/conda-environment.yaml
2023-07-10 19:20:54,130 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:20:54,130 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/requirements.txt
2023-07-10 19:20:54,147 DEBUG   HandlerThread:28768 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 19:20:54,147 INFO    HandlerThread:28768 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 19:20:54,149 DEBUG   SenderThread:28768 [sender.py:send():369] send: files
2023-07-10 19:20:54,149 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 19:20:54,152 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:20:54,152 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:20:54,614 ERROR   wandb-upload_0:28768 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/wandb-metadata.json?Expires=1689074454&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xLgxY%2BJyfnYqkglzV7KEsPVSaUmwJi1zlex%2FoQmC7cvrKnPawA2C%2FpxwZ%2BWNHvPSp8jJUHEGAuC7PQRjdSw3MtLBI5jUgRAAf7fnLqTL0K9es2%2BxJEBUgP2r4Agq%2FjwMZhUT9h13I7SdN%2FCvReN3L77GSuv6z%2F0qF46AKYbW%2FJ74TVHNvroxi%2ByYL9pjj%2B9GjVpYtB8JmkseYggeHASgprYV1T7VG2F8pZGEI5mxHymy7fenJHL%2BauHLMdmf9bYm9%2BgoK%2Fpv5NDZn2JRopTcA3EmDCf90kNxlg3iYAD%2B%2FR0N4Oj1qIP2RbVZPwr2aySaD7S48WJGdeF38Alytyxx5Q%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/wandb-metadata.json?Expires=1689074454&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xLgxY%2BJyfnYqkglzV7KEsPVSaUmwJi1zlex%2FoQmC7cvrKnPawA2C%2FpxwZ%2BWNHvPSp8jJUHEGAuC7PQRjdSw3MtLBI5jUgRAAf7fnLqTL0K9es2%2BxJEBUgP2r4Agq%2FjwMZhUT9h13I7SdN%2FCvReN3L77GSuv6z%2F0qF46AKYbW%2FJ74TVHNvroxi%2ByYL9pjj%2B9GjVpYtB8JmkseYggeHASgprYV1T7VG2F8pZGEI5mxHymy7fenJHL%2BauHLMdmf9bYm9%2BgoK%2Fpv5NDZn2JRopTcA3EmDCf90kNxlg3iYAD%2B%2FR0N4Oj1qIP2RbVZPwr2aySaD7S48WJGdeF38Alytyxx5Q%3D%3D
2023-07-10 19:20:54,614 ERROR   wandb-upload_0:28768 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3693'}
2023-07-10 19:20:54,615 ERROR   wandb-upload_0:28768 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:20:54,748 DEBUG   SenderThread:28768 [sender.py:send():369] send: telemetry
2023-07-10 19:20:55,130 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:20:55,130 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-metadata.json
2023-07-10 19:20:55,159 ERROR   wandb-upload_0:28768 [upload_job.py:push():136] Failed to upload file: /tmp/tmpw8iz0h0ewandb/g3h0cc1v-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/wandb-metadata.json?Expires=1689074454&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xLgxY%2BJyfnYqkglzV7KEsPVSaUmwJi1zlex%2FoQmC7cvrKnPawA2C%2FpxwZ%2BWNHvPSp8jJUHEGAuC7PQRjdSw3MtLBI5jUgRAAf7fnLqTL0K9es2%2BxJEBUgP2r4Agq%2FjwMZhUT9h13I7SdN%2FCvReN3L77GSuv6z%2F0qF46AKYbW%2FJ74TVHNvroxi%2ByYL9pjj%2B9GjVpYtB8JmkseYggeHASgprYV1T7VG2F8pZGEI5mxHymy7fenJHL%2BauHLMdmf9bYm9%2BgoK%2Fpv5NDZn2JRopTcA3EmDCf90kNxlg3iYAD%2B%2FR0N4Oj1qIP2RbVZPwr2aySaD7S48WJGdeF38Alytyxx5Q%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:20:55,364 ERROR   Thread-11 :28768 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpw8iz0h0ewandb/g3h0cc1v-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/wandb-metadata.json?Expires=1689074454&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xLgxY%2BJyfnYqkglzV7KEsPVSaUmwJi1zlex%2FoQmC7cvrKnPawA2C%2FpxwZ%2BWNHvPSp8jJUHEGAuC7PQRjdSw3MtLBI5jUgRAAf7fnLqTL0K9es2%2BxJEBUgP2r4Agq%2FjwMZhUT9h13I7SdN%2FCvReN3L77GSuv6z%2F0qF46AKYbW%2FJ74TVHNvroxi%2ByYL9pjj%2B9GjVpYtB8JmkseYggeHASgprYV1T7VG2F8pZGEI5mxHymy7fenJHL%2BauHLMdmf9bYm9%2BgoK%2Fpv5NDZn2JRopTcA3EmDCf90kNxlg3iYAD%2B%2FR0N4Oj1qIP2RbVZPwr2aySaD7S48WJGdeF38Alytyxx5Q%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:20:57,130 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:20:57,286 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:20:59,131 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:21:02,346 DEBUG   SenderThread:28768 [sender.py:send():369] send: telemetry
2023-07-10 19:21:02,346 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:21:03,132 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:21:05,132 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:21:07,364 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:21:09,133 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:21:09,152 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:21:09,152 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:21:12,378 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:21:17,378 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:21:22,382 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:21:23,136 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/config.yaml
2023-07-10 19:21:24,152 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:21:24,152 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:21:28,381 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:21:33,382 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:21:38,382 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:21:38,912 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:21:38,912 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:21:38,913 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:21:38,913 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:21:39,140 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:21:39,158 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:21:39,158 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:21:41,141 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:21:43,387 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:21:48,387 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:21:53,315 DEBUG   SystemMonitor:28768 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-10 19:21:53,315 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:21:54,152 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:21:54,158 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:21:54,158 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:21:59,402 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:22:04,403 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:22:09,158 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:22:09,158 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:22:09,329 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:22:09,385 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:22:09,386 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:22:09,387 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:22:10,151 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:22:10,387 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:22:11,152 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:22:15,387 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:22:20,388 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:22:23,316 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:22:24,158 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:22:24,158 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:22:25,437 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:22:30,437 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:22:35,438 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:22:39,158 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:22:39,158 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:22:40,086 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:22:40,088 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:22:40,088 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:22:40,088 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:22:40,160 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:22:41,088 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:22:41,160 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:22:46,089 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:22:51,090 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:22:53,316 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:22:54,158 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:22:54,158 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:22:56,389 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:23:01,389 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:23:06,390 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:23:09,162 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:23:09,162 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:23:10,795 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:23:10,796 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:23:10,796 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:23:10,797 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:23:11,166 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:23:11,797 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:23:13,167 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:23:16,798 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:23:21,798 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:23:23,317 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:23:24,162 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:23:24,162 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:23:27,396 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:23:32,397 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:23:37,397 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:23:39,162 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:23:39,162 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:23:41,070 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:23:41,070 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:23:41,070 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:23:41,071 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:23:41,179 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:23:43,071 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:23:43,179 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:23:48,072 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:23:53,073 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:23:53,317 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:23:54,162 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:23:54,162 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:23:58,452 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:24:03,453 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:24:08,453 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:24:09,162 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:24:09,162 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:24:11,406 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:24:11,407 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:24:11,407 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:24:11,407 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:24:12,186 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:24:13,186 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:24:14,408 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:24:19,408 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:24:23,317 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:24:24,162 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:24:24,163 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:24:25,389 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:24:30,390 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:24:35,390 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:24:39,163 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:24:39,163 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:24:40,394 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:24:42,466 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:24:42,466 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:24:42,467 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:24:42,467 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:24:43,193 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:24:43,193 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:24:45,467 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:24:50,468 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:24:53,318 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:24:54,163 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:24:54,163 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:24:56,401 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:25:01,401 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:25:06,402 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:25:09,163 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:25:09,163 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:25:12,390 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:25:13,078 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:25:13,079 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:25:13,079 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:25:13,079 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:25:13,199 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:25:15,200 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:25:18,080 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:25:23,080 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:25:23,319 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:25:24,163 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:25:24,163 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:25:28,403 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:25:33,403 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:25:38,404 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:25:39,163 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:25:39,163 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:25:43,749 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:25:43,749 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:25:43,749 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:25:43,750 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:25:43,750 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:25:44,206 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:25:45,206 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:25:48,751 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:25:53,319 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:25:54,154 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:25:54,163 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:25:54,163 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:25:59,394 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:26:04,394 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:26:09,163 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:26:09,164 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:26:10,392 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:26:14,036 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:26:14,036 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:26:14,036 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:26:14,037 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:26:14,212 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:26:15,212 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:26:16,038 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:26:21,038 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:26:23,320 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:26:24,163 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:26:24,164 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:26:26,410 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:26:31,410 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:26:36,411 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:26:39,163 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:26:39,163 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:26:42,398 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:26:45,498 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:26:45,499 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:26:45,499 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:26:45,500 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:26:46,219 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:26:47,220 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:26:47,501 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:26:52,501 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:26:53,321 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:26:54,163 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:26:54,164 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:26:58,471 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:27:03,472 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:27:08,473 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:27:09,170 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:27:09,170 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:27:14,430 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:27:16,522 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:27:16,523 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:27:16,523 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:27:16,524 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:27:17,226 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:27:17,226 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:27:19,525 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:27:23,322 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:27:24,170 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:27:24,170 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:27:25,401 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:27:30,402 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:27:35,402 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:27:39,170 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:27:39,170 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:27:41,400 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:27:46,401 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:27:47,373 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:27:47,373 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:27:47,373 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:27:47,374 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:27:48,233 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:27:49,233 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:27:52,375 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:27:53,322 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:27:54,170 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:27:54,171 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:27:57,405 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:28:02,406 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:28:07,406 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:28:09,170 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:28:09,170 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:28:13,401 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:28:18,056 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:28:18,057 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:28:18,057 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:28:18,058 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:28:18,240 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:28:19,058 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:28:19,240 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:28:23,323 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:28:24,155 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:28:24,171 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:28:24,171 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:28:29,438 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:28:34,439 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:28:39,171 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:28:39,171 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:28:40,412 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:28:45,412 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:28:48,023 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:28:48,024 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:28:48,024 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:28:48,024 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:28:48,247 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:28:50,247 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:28:51,025 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:28:53,324 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:28:54,171 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:28:54,171 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:28:56,406 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:29:01,407 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:29:06,407 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:29:09,171 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:29:09,171 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:29:11,411 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:29:16,412 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:29:20,390 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:29:20,390 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:29:20,390 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:29:20,391 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:29:21,254 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:29:22,254 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:29:22,392 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:29:23,324 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:29:24,171 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:29:24,172 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:29:27,405 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:29:32,406 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:29:37,406 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:29:39,171 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:29:39,171 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:29:43,401 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:29:48,401 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:29:51,621 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:29:51,621 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:29:51,622 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:29:51,623 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:29:52,261 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:29:53,325 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:29:54,155 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:29:54,171 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:29:54,171 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:29:54,261 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:29:59,398 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:30:04,399 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:30:09,171 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:30:09,172 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:30:10,397 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:30:15,398 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:30:20,399 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:30:22,541 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:30:22,542 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:30:22,542 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:30:22,543 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:30:23,268 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:30:23,325 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:30:24,171 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:30:24,171 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:30:24,268 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:30:25,401 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:30:30,402 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:30:35,402 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:30:39,171 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:30:39,172 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:30:40,405 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:30:45,406 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:30:50,406 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:30:53,326 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:30:53,685 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:30:53,686 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:30:53,686 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:30:53,687 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:30:54,172 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:30:54,172 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:30:54,275 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:30:56,275 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:30:56,400 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:31:01,400 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:31:06,401 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:31:09,172 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:31:09,172 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:31:11,407 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:31:16,407 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:31:21,408 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:31:23,326 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:31:24,153 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:31:24,154 DEBUG   SenderThread:28768 [sender.py:send():369] send: history
2023-07-10 19:31:24,154 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:31:24,154 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:31:24,172 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:31:24,172 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:31:24,284 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:31:25,296 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: poll_exit
2023-07-10 19:31:26,285 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:31:28,141 DEBUG   SenderThread:28768 [sender.py:send():369] send: exit
2023-07-10 19:31:28,141 INFO    SenderThread:28768 [sender.py:send_exit():574] handling exit code: 1
2023-07-10 19:31:28,141 INFO    SenderThread:28768 [sender.py:send_exit():576] handling runtime: 630
2023-07-10 19:31:28,141 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:31:28,142 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:31:28,142 INFO    SenderThread:28768 [sender.py:send_exit():582] send defer
2023-07-10 19:31:28,142 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: poll_exit
2023-07-10 19:31:28,142 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:31:28,142 INFO    HandlerThread:28768 [handler.py:handle_request_defer():170] handle defer: 0
2023-07-10 19:31:28,143 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: defer
2023-07-10 19:31:28,143 INFO    SenderThread:28768 [sender.py:send_request_defer():598] handle sender defer: 0
2023-07-10 19:31:28,143 INFO    SenderThread:28768 [sender.py:transition_state():602] send defer: 1
2023-07-10 19:31:28,143 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:31:28,143 INFO    HandlerThread:28768 [handler.py:handle_request_defer():170] handle defer: 1
2023-07-10 19:31:28,143 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: defer
2023-07-10 19:31:28,143 INFO    SenderThread:28768 [sender.py:send_request_defer():598] handle sender defer: 1
2023-07-10 19:31:28,143 INFO    SenderThread:28768 [sender.py:transition_state():602] send defer: 2
2023-07-10 19:31:28,143 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:31:28,143 INFO    HandlerThread:28768 [handler.py:handle_request_defer():170] handle defer: 2
2023-07-10 19:31:28,143 INFO    HandlerThread:28768 [system_monitor.py:finish():190] Stopping system monitor
2023-07-10 19:31:28,143 DEBUG   SystemMonitor:28768 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-07-10 19:31:28,143 DEBUG   SystemMonitor:28768 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-07-10 19:31:28,144 INFO    HandlerThread:28768 [interfaces.py:finish():202] Joined cpu monitor
2023-07-10 19:31:28,144 INFO    HandlerThread:28768 [interfaces.py:finish():202] Joined disk monitor
2023-07-10 19:31:28,206 INFO    HandlerThread:28768 [interfaces.py:finish():202] Joined gpu monitor
2023-07-10 19:31:28,206 INFO    HandlerThread:28768 [interfaces.py:finish():202] Joined memory monitor
2023-07-10 19:31:28,206 INFO    HandlerThread:28768 [interfaces.py:finish():202] Joined network monitor
2023-07-10 19:31:28,206 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: defer
2023-07-10 19:31:28,206 INFO    SenderThread:28768 [sender.py:send_request_defer():598] handle sender defer: 2
2023-07-10 19:31:28,207 INFO    SenderThread:28768 [sender.py:transition_state():602] send defer: 3
2023-07-10 19:31:28,207 DEBUG   SenderThread:28768 [sender.py:send():369] send: stats
2023-07-10 19:31:28,207 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:31:28,207 INFO    HandlerThread:28768 [handler.py:handle_request_defer():170] handle defer: 3
2023-07-10 19:31:28,207 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: defer
2023-07-10 19:31:28,207 INFO    SenderThread:28768 [sender.py:send_request_defer():598] handle sender defer: 3
2023-07-10 19:31:28,207 INFO    SenderThread:28768 [sender.py:transition_state():602] send defer: 4
2023-07-10 19:31:28,207 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:31:28,207 INFO    HandlerThread:28768 [handler.py:handle_request_defer():170] handle defer: 4
2023-07-10 19:31:28,208 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: defer
2023-07-10 19:31:28,208 INFO    SenderThread:28768 [sender.py:send_request_defer():598] handle sender defer: 4
2023-07-10 19:31:28,208 INFO    SenderThread:28768 [sender.py:transition_state():602] send defer: 5
2023-07-10 19:31:28,208 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:31:28,208 INFO    HandlerThread:28768 [handler.py:handle_request_defer():170] handle defer: 5
2023-07-10 19:31:28,208 DEBUG   SenderThread:28768 [sender.py:send():369] send: summary
2023-07-10 19:31:28,208 INFO    SenderThread:28768 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:31:28,208 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: defer
2023-07-10 19:31:28,208 INFO    SenderThread:28768 [sender.py:send_request_defer():598] handle sender defer: 5
2023-07-10 19:31:28,208 INFO    SenderThread:28768 [sender.py:transition_state():602] send defer: 6
2023-07-10 19:31:28,209 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:31:28,209 INFO    HandlerThread:28768 [handler.py:handle_request_defer():170] handle defer: 6
2023-07-10 19:31:28,209 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: defer
2023-07-10 19:31:28,209 INFO    SenderThread:28768 [sender.py:send_request_defer():598] handle sender defer: 6
2023-07-10 19:31:28,209 INFO    SenderThread:28768 [sender.py:transition_state():602] send defer: 7
2023-07-10 19:31:28,209 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:31:28,209 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:31:28,209 INFO    HandlerThread:28768 [handler.py:handle_request_defer():170] handle defer: 7
2023-07-10 19:31:28,209 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: defer
2023-07-10 19:31:28,209 INFO    SenderThread:28768 [sender.py:send_request_defer():598] handle sender defer: 7
2023-07-10 19:31:28,285 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
2023-07-10 19:31:30,286 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:31:30,297 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: keepalive
2023-07-10 19:31:31,381 INFO    SenderThread:28768 [sender.py:transition_state():602] send defer: 8
2023-07-10 19:31:31,381 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:31:31,381 INFO    HandlerThread:28768 [handler.py:handle_request_defer():170] handle defer: 8
2023-07-10 19:31:31,381 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: defer
2023-07-10 19:31:31,381 INFO    SenderThread:28768 [sender.py:send_request_defer():598] handle sender defer: 8
2023-07-10 19:31:31,381 INFO    SenderThread:28768 [job_builder.py:build():232] Attempting to build job artifact
2023-07-10 19:31:31,382 INFO    SenderThread:28768 [job_builder.py:build():266] no source found
2023-07-10 19:31:31,382 INFO    SenderThread:28768 [sender.py:transition_state():602] send defer: 9
2023-07-10 19:31:31,382 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:31:31,382 INFO    HandlerThread:28768 [handler.py:handle_request_defer():170] handle defer: 9
2023-07-10 19:31:31,382 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: defer
2023-07-10 19:31:31,382 INFO    SenderThread:28768 [sender.py:send_request_defer():598] handle sender defer: 9
2023-07-10 19:31:31,382 INFO    SenderThread:28768 [dir_watcher.py:finish():359] shutting down directory watcher
2023-07-10 19:31:32,286 INFO    Thread-12 :28768 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
2023-07-10 19:31:32,287 INFO    SenderThread:28768 [dir_watcher.py:finish():389] scan: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files
2023-07-10 19:31:32,287 INFO    SenderThread:28768 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-metadata.json wandb-metadata.json
2023-07-10 19:31:32,287 INFO    SenderThread:28768 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/config.yaml config.yaml
2023-07-10 19:31:32,287 INFO    SenderThread:28768 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/requirements.txt requirements.txt
2023-07-10 19:31:32,287 INFO    SenderThread:28768 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json wandb-summary.json
2023-07-10 19:31:32,287 INFO    SenderThread:28768 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/conda-environment.yaml conda-environment.yaml
2023-07-10 19:31:32,287 INFO    SenderThread:28768 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log output.log
2023-07-10 19:31:32,289 INFO    SenderThread:28768 [sender.py:transition_state():602] send defer: 10
2023-07-10 19:31:32,290 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:31:32,290 INFO    HandlerThread:28768 [handler.py:handle_request_defer():170] handle defer: 10
2023-07-10 19:31:32,293 DEBUG   SenderThread:28768 [sender.py:send_request():396] send_request: defer
2023-07-10 19:31:32,294 INFO    SenderThread:28768 [sender.py:send_request_defer():598] handle sender defer: 10
2023-07-10 19:31:32,294 INFO    SenderThread:28768 [file_pusher.py:finish():159] shutting down file pusher
2023-07-10 19:31:32,773 ERROR   wandb-upload_0:28768 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/config.yaml?Expires=1689075092&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=odi3FpTXbnPMBsbq23RaECc8N3K2NVp7006EO4GoWzY6fy4w2byvw7nh15tmL7os5gbc1baSaVIPO4F70sjOOztHEIiz2fbg9Q%2FMvxqBQSlVIp2vkwebLjIhqJm%2BvK0LdsCv0BDNRS2jFQBg86PjYYyFhWfw7TT%2B7TSRK4fi2ZvRbtp7jsUvYEXMcfNtePAE99ueJuM4ICIVhXMFCDfxWV3pGP9POjpmWCt4PO3o9AdbE0SkiAcJ1pj4FPVEqWTFmO7HTqea9vWmK76%2FSS%2F4xkU33ZoyzzlDNlfhIGM2IMTZMkm61gYW0zAPImGskGIcUBtOUJMF%2BWhllsC%2BlymLAQ%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/config.yaml?Expires=1689075092&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=odi3FpTXbnPMBsbq23RaECc8N3K2NVp7006EO4GoWzY6fy4w2byvw7nh15tmL7os5gbc1baSaVIPO4F70sjOOztHEIiz2fbg9Q%2FMvxqBQSlVIp2vkwebLjIhqJm%2BvK0LdsCv0BDNRS2jFQBg86PjYYyFhWfw7TT%2B7TSRK4fi2ZvRbtp7jsUvYEXMcfNtePAE99ueJuM4ICIVhXMFCDfxWV3pGP9POjpmWCt4PO3o9AdbE0SkiAcJ1pj4FPVEqWTFmO7HTqea9vWmK76%2FSS%2F4xkU33ZoyzzlDNlfhIGM2IMTZMkm61gYW0zAPImGskGIcUBtOUJMF%2BWhllsC%2BlymLAQ%3D%3D
2023-07-10 19:31:32,774 ERROR   wandb-upload_0:28768 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '525'}
2023-07-10 19:31:32,774 ERROR   wandb-upload_0:28768 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/config.yaml</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:31:33,294 DEBUG   HandlerThread:28768 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:31:33,893 WARNING StreamThr :28768 [internal.py:is_dead():414] Internal process exiting, parent pid 28738 disappeared
2023-07-10 19:31:33,893 ERROR   StreamThr :28768 [internal.py:wandb_internal():152] Internal process shutdown.
2023-07-10 19:31:34,294 INFO    SenderThread:28768 [sender.py:finish():1526] shutting down sender
2023-07-10 19:31:34,294 INFO    SenderThread:28768 [file_pusher.py:finish():159] shutting down file pusher
2023-07-10 19:31:34,295 INFO    SenderThread:28768 [file_pusher.py:join():164] waiting for file pusher
2023-07-10 19:31:34,295 INFO    HandlerThread:28768 [handler.py:finish():854] shutting down handler
2023-07-10 19:31:34,295 INFO    WriterThread:28768 [datastore.py:close():298] close: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/run-8ni8xi78.wandb
2023-07-10 19:31:34,496 ERROR   wandb-upload_0:28768 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/config.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/config.yaml?Expires=1689075092&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=odi3FpTXbnPMBsbq23RaECc8N3K2NVp7006EO4GoWzY6fy4w2byvw7nh15tmL7os5gbc1baSaVIPO4F70sjOOztHEIiz2fbg9Q%2FMvxqBQSlVIp2vkwebLjIhqJm%2BvK0LdsCv0BDNRS2jFQBg86PjYYyFhWfw7TT%2B7TSRK4fi2ZvRbtp7jsUvYEXMcfNtePAE99ueJuM4ICIVhXMFCDfxWV3pGP9POjpmWCt4PO3o9AdbE0SkiAcJ1pj4FPVEqWTFmO7HTqea9vWmK76%2FSS%2F4xkU33ZoyzzlDNlfhIGM2IMTZMkm61gYW0zAPImGskGIcUBtOUJMF%2BWhllsC%2BlymLAQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:31:34,700 ERROR   Thread-11 :28768 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/config.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/config.yaml?Expires=1689075092&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=odi3FpTXbnPMBsbq23RaECc8N3K2NVp7006EO4GoWzY6fy4w2byvw7nh15tmL7os5gbc1baSaVIPO4F70sjOOztHEIiz2fbg9Q%2FMvxqBQSlVIp2vkwebLjIhqJm%2BvK0LdsCv0BDNRS2jFQBg86PjYYyFhWfw7TT%2B7TSRK4fi2ZvRbtp7jsUvYEXMcfNtePAE99ueJuM4ICIVhXMFCDfxWV3pGP9POjpmWCt4PO3o9AdbE0SkiAcJ1pj4FPVEqWTFmO7HTqea9vWmK76%2FSS%2F4xkU33ZoyzzlDNlfhIGM2IMTZMkm61gYW0zAPImGskGIcUBtOUJMF%2BWhllsC%2BlymLAQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:31:34,875 ERROR   wandb-upload_1:28768 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/requirements.txt?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AEgDiTyX2beF%2B8qlPJAq04y54lPO7kZHE4Dm1VLYfQcubMgloYnmeSvqN%2F3fAd4wtXKOhSFRkHZe1WZJN%2FX49CdJO6ViUOlFzOAHFUdfhSSGlzSJjfMFDe79UV32MKASsvu56fhg%2FSsm9GVuw6ecLuOvJQFJmOsUmqBEl%2BiA9ZJi%2F9a9MTjETjBL9CDldfwNXquDc5hJnSRXV%2BooSV16ZzScToXGI6x9zAUrZL8dTHiqvcgNG6e4JqAmihtCOdbGkWhUTmfU%2FGWBk4ptDxgb5jkLmjXJVMVC7zTWOCH2nniKnfB%2BclOYEF7kf%2FN5%2F5p7HEQThaAG6fK1iKDRgQtfZQ%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/requirements.txt?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AEgDiTyX2beF%2B8qlPJAq04y54lPO7kZHE4Dm1VLYfQcubMgloYnmeSvqN%2F3fAd4wtXKOhSFRkHZe1WZJN%2FX49CdJO6ViUOlFzOAHFUdfhSSGlzSJjfMFDe79UV32MKASsvu56fhg%2FSsm9GVuw6ecLuOvJQFJmOsUmqBEl%2BiA9ZJi%2F9a9MTjETjBL9CDldfwNXquDc5hJnSRXV%2BooSV16ZzScToXGI6x9zAUrZL8dTHiqvcgNG6e4JqAmihtCOdbGkWhUTmfU%2FGWBk4ptDxgb5jkLmjXJVMVC7zTWOCH2nniKnfB%2BclOYEF7kf%2FN5%2F5p7HEQThaAG6fK1iKDRgQtfZQ%3D%3D
2023-07-10 19:31:34,875 ERROR   wandb-upload_1:28768 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '926'}
2023-07-10 19:31:34,875 ERROR   wandb-upload_1:28768 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/requirements.txt</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:31:34,877 ERROR   wandb-upload_4:28768 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/output.log?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKrNg%2BHT82pCNdK7vavZN9tuqb5B2wVefDbpwv9cLDoc5YqirM2pOzTcRFLc2Mf%2FujCxB7i8QFUIvSv0cBOTVxkmAEroGtCbpFqbNh57XY8ir%2Fr3DBL%2F59hpfr1tduirtdIMxDObOQgJUs85GZXD4kgdcABV4kmzyHBbvJIcfmNyDAgfUTIgpq0jkTHsMOPwG6BaXUzYJdR4HW1oX0%2FDhV9zM4KxSNllhRjC94uExHC4ZVBGoePBvQoxNyuJzZGUPJgUrpJ8N28iAhpFPKkEIBJbxla3Rl7fsXguMyTGynlGtDPcYbGX2Kt0MRcsC8oB1BNZ%2BLx8kWY7P%2FubB6ZJuw%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/output.log?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKrNg%2BHT82pCNdK7vavZN9tuqb5B2wVefDbpwv9cLDoc5YqirM2pOzTcRFLc2Mf%2FujCxB7i8QFUIvSv0cBOTVxkmAEroGtCbpFqbNh57XY8ir%2Fr3DBL%2F59hpfr1tduirtdIMxDObOQgJUs85GZXD4kgdcABV4kmzyHBbvJIcfmNyDAgfUTIgpq0jkTHsMOPwG6BaXUzYJdR4HW1oX0%2FDhV9zM4KxSNllhRjC94uExHC4ZVBGoePBvQoxNyuJzZGUPJgUrpJ8N28iAhpFPKkEIBJbxla3Rl7fsXguMyTGynlGtDPcYbGX2Kt0MRcsC8oB1BNZ%2BLx8kWY7P%2FubB6ZJuw%3D%3D
2023-07-10 19:31:34,877 ERROR   wandb-upload_4:28768 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '28321'}
2023-07-10 19:31:34,877 ERROR   wandb-upload_4:28768 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/output.log</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:31:34,888 ERROR   wandb-upload_3:28768 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/conda-environment.yaml?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=q1iPEWryM3fhPcBvjj6%2BZxXz61aKTEwDv10BrDM3ClvUrJBbDG4zzxX4oy%2FaYUkiLD8jCL9h0h83WbtUOZbUZ1W3ma5AOonjBAMNo9YKUAgVedDRKBb5P63Q557Ttd3m03rmQKQaULBpOAwG6ykM0ZcGX1b3RplR5QESiANx%2FT9ZYf5hO005ztIpgij8YP60vBeO5Dp7vbBWH3i4IXe5tPdWKtX7yyfBrJJq2EPXfr0%2BTV2R9pAswY6UmhmKJn%2Bswvow8LxOb5uA7kpug8G5gxlLILzQwYAuZUn5p6dsVe3qrJSX1Cy4T5TLznHDM7vuxj%2F1AqyKVBPkwHWSaFwhjg%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/conda-environment.yaml?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=q1iPEWryM3fhPcBvjj6%2BZxXz61aKTEwDv10BrDM3ClvUrJBbDG4zzxX4oy%2FaYUkiLD8jCL9h0h83WbtUOZbUZ1W3ma5AOonjBAMNo9YKUAgVedDRKBb5P63Q557Ttd3m03rmQKQaULBpOAwG6ykM0ZcGX1b3RplR5QESiANx%2FT9ZYf5hO005ztIpgij8YP60vBeO5Dp7vbBWH3i4IXe5tPdWKtX7yyfBrJJq2EPXfr0%2BTV2R9pAswY6UmhmKJn%2Bswvow8LxOb5uA7kpug8G5gxlLILzQwYAuZUn5p6dsVe3qrJSX1Cy4T5TLznHDM7vuxj%2F1AqyKVBPkwHWSaFwhjg%3D%3D
2023-07-10 19:31:34,888 ERROR   wandb-upload_3:28768 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1925'}
2023-07-10 19:31:34,888 ERROR   wandb-upload_3:28768 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/conda-environment.yaml</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:31:34,905 ERROR   wandb-upload_2:28768 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/wandb-summary.json?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=D6nErG9YifmCZGgNqn5FHhvUEeSAup%2FybSR%2BoJKG4X3fFNIb2HbXuLdHW%2FyyT0D9P0ySyM75N8EA2cfCk3EJVY2O%2B88W5kTz8T%2BcZg9ca%2Fjjop9QZlcFKkirPjHQsE4FQPBzEb2NcxYaZ7eoIFc%2FLTlqXa0Bl4%2F5IuYDMRP%2Fxexvfblv8oet7oIfJdzc5u6FIxHkDD0FymBlawRQoTM7YxnRUJ%2FczjKYumms3NE38eRMCSXPenTOWsMVxOkoEGCUqugTyl9bYgeBR1m9Gfwadj6cJ3%2FEVGjLFJtZEN9RRfKa%2FX2CjgqwH087TRp83ZgV7Mq1hwv4BlbWbvw0uTo%2B%2FQ%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/wandb-summary.json?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=D6nErG9YifmCZGgNqn5FHhvUEeSAup%2FybSR%2BoJKG4X3fFNIb2HbXuLdHW%2FyyT0D9P0ySyM75N8EA2cfCk3EJVY2O%2B88W5kTz8T%2BcZg9ca%2Fjjop9QZlcFKkirPjHQsE4FQPBzEb2NcxYaZ7eoIFc%2FLTlqXa0Bl4%2F5IuYDMRP%2Fxexvfblv8oet7oIfJdzc5u6FIxHkDD0FymBlawRQoTM7YxnRUJ%2FczjKYumms3NE38eRMCSXPenTOWsMVxOkoEGCUqugTyl9bYgeBR1m9Gfwadj6cJ3%2FEVGjLFJtZEN9RRfKa%2FX2CjgqwH087TRp83ZgV7Mq1hwv4BlbWbvw0uTo%2B%2FQ%3D%3D
2023-07-10 19:31:34,905 ERROR   wandb-upload_2:28768 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '163'}
2023-07-10 19:31:34,905 ERROR   wandb-upload_2:28768 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/wandb-summary.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:31:35,685 ERROR   wandb-upload_1:28768 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/requirements.txt
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/requirements.txt?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AEgDiTyX2beF%2B8qlPJAq04y54lPO7kZHE4Dm1VLYfQcubMgloYnmeSvqN%2F3fAd4wtXKOhSFRkHZe1WZJN%2FX49CdJO6ViUOlFzOAHFUdfhSSGlzSJjfMFDe79UV32MKASsvu56fhg%2FSsm9GVuw6ecLuOvJQFJmOsUmqBEl%2BiA9ZJi%2F9a9MTjETjBL9CDldfwNXquDc5hJnSRXV%2BooSV16ZzScToXGI6x9zAUrZL8dTHiqvcgNG6e4JqAmihtCOdbGkWhUTmfU%2FGWBk4ptDxgb5jkLmjXJVMVC7zTWOCH2nniKnfB%2BclOYEF7kf%2FN5%2F5p7HEQThaAG6fK1iKDRgQtfZQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:31:35,685 ERROR   wandb-upload_4:28768 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/output.log?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKrNg%2BHT82pCNdK7vavZN9tuqb5B2wVefDbpwv9cLDoc5YqirM2pOzTcRFLc2Mf%2FujCxB7i8QFUIvSv0cBOTVxkmAEroGtCbpFqbNh57XY8ir%2Fr3DBL%2F59hpfr1tduirtdIMxDObOQgJUs85GZXD4kgdcABV4kmzyHBbvJIcfmNyDAgfUTIgpq0jkTHsMOPwG6BaXUzYJdR4HW1oX0%2FDhV9zM4KxSNllhRjC94uExHC4ZVBGoePBvQoxNyuJzZGUPJgUrpJ8N28iAhpFPKkEIBJbxla3Rl7fsXguMyTGynlGtDPcYbGX2Kt0MRcsC8oB1BNZ%2BLx8kWY7P%2FubB6ZJuw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:31:35,686 ERROR   wandb-upload_3:28768 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/conda-environment.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/conda-environment.yaml?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=q1iPEWryM3fhPcBvjj6%2BZxXz61aKTEwDv10BrDM3ClvUrJBbDG4zzxX4oy%2FaYUkiLD8jCL9h0h83WbtUOZbUZ1W3ma5AOonjBAMNo9YKUAgVedDRKBb5P63Q557Ttd3m03rmQKQaULBpOAwG6ykM0ZcGX1b3RplR5QESiANx%2FT9ZYf5hO005ztIpgij8YP60vBeO5Dp7vbBWH3i4IXe5tPdWKtX7yyfBrJJq2EPXfr0%2BTV2R9pAswY6UmhmKJn%2Bswvow8LxOb5uA7kpug8G5gxlLILzQwYAuZUn5p6dsVe3qrJSX1Cy4T5TLznHDM7vuxj%2F1AqyKVBPkwHWSaFwhjg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:31:35,686 ERROR   wandb-upload_2:28768 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/wandb-summary.json?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=D6nErG9YifmCZGgNqn5FHhvUEeSAup%2FybSR%2BoJKG4X3fFNIb2HbXuLdHW%2FyyT0D9P0ySyM75N8EA2cfCk3EJVY2O%2B88W5kTz8T%2BcZg9ca%2Fjjop9QZlcFKkirPjHQsE4FQPBzEb2NcxYaZ7eoIFc%2FLTlqXa0Bl4%2F5IuYDMRP%2Fxexvfblv8oet7oIfJdzc5u6FIxHkDD0FymBlawRQoTM7YxnRUJ%2FczjKYumms3NE38eRMCSXPenTOWsMVxOkoEGCUqugTyl9bYgeBR1m9Gfwadj6cJ3%2FEVGjLFJtZEN9RRfKa%2FX2CjgqwH087TRp83ZgV7Mq1hwv4BlbWbvw0uTo%2B%2FQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:31:36,503 ERROR   Thread-11 :28768 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/requirements.txt
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/requirements.txt?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AEgDiTyX2beF%2B8qlPJAq04y54lPO7kZHE4Dm1VLYfQcubMgloYnmeSvqN%2F3fAd4wtXKOhSFRkHZe1WZJN%2FX49CdJO6ViUOlFzOAHFUdfhSSGlzSJjfMFDe79UV32MKASsvu56fhg%2FSsm9GVuw6ecLuOvJQFJmOsUmqBEl%2BiA9ZJi%2F9a9MTjETjBL9CDldfwNXquDc5hJnSRXV%2BooSV16ZzScToXGI6x9zAUrZL8dTHiqvcgNG6e4JqAmihtCOdbGkWhUTmfU%2FGWBk4ptDxgb5jkLmjXJVMVC7zTWOCH2nniKnfB%2BclOYEF7kf%2FN5%2F5p7HEQThaAG6fK1iKDRgQtfZQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:31:36,503 ERROR   Thread-11 :28768 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/output.log
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/output.log?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKrNg%2BHT82pCNdK7vavZN9tuqb5B2wVefDbpwv9cLDoc5YqirM2pOzTcRFLc2Mf%2FujCxB7i8QFUIvSv0cBOTVxkmAEroGtCbpFqbNh57XY8ir%2Fr3DBL%2F59hpfr1tduirtdIMxDObOQgJUs85GZXD4kgdcABV4kmzyHBbvJIcfmNyDAgfUTIgpq0jkTHsMOPwG6BaXUzYJdR4HW1oX0%2FDhV9zM4KxSNllhRjC94uExHC4ZVBGoePBvQoxNyuJzZGUPJgUrpJ8N28iAhpFPKkEIBJbxla3Rl7fsXguMyTGynlGtDPcYbGX2Kt0MRcsC8oB1BNZ%2BLx8kWY7P%2FubB6ZJuw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:31:36,503 ERROR   Thread-11 :28768 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/wandb-summary.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/wandb-summary.json?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=D6nErG9YifmCZGgNqn5FHhvUEeSAup%2FybSR%2BoJKG4X3fFNIb2HbXuLdHW%2FyyT0D9P0ySyM75N8EA2cfCk3EJVY2O%2B88W5kTz8T%2BcZg9ca%2Fjjop9QZlcFKkirPjHQsE4FQPBzEb2NcxYaZ7eoIFc%2FLTlqXa0Bl4%2F5IuYDMRP%2Fxexvfblv8oet7oIfJdzc5u6FIxHkDD0FymBlawRQoTM7YxnRUJ%2FczjKYumms3NE38eRMCSXPenTOWsMVxOkoEGCUqugTyl9bYgeBR1m9Gfwadj6cJ3%2FEVGjLFJtZEN9RRfKa%2FX2CjgqwH087TRp83ZgV7Mq1hwv4BlbWbvw0uTo%2B%2FQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:31:36,503 ERROR   Thread-11 :28768 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_192052-8ni8xi78/files/conda-environment.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/8ni8xi78/conda-environment.yaml?Expires=1689075094&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=q1iPEWryM3fhPcBvjj6%2BZxXz61aKTEwDv10BrDM3ClvUrJBbDG4zzxX4oy%2FaYUkiLD8jCL9h0h83WbtUOZbUZ1W3ma5AOonjBAMNo9YKUAgVedDRKBb5P63Q557Ttd3m03rmQKQaULBpOAwG6ykM0ZcGX1b3RplR5QESiANx%2FT9ZYf5hO005ztIpgij8YP60vBeO5Dp7vbBWH3i4IXe5tPdWKtX7yyfBrJJq2EPXfr0%2BTV2R9pAswY6UmhmKJn%2Bswvow8LxOb5uA7kpug8G5gxlLILzQwYAuZUn5p6dsVe3qrJSX1Cy4T5TLznHDM7vuxj%2F1AqyKVBPkwHWSaFwhjg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:31:36,703 INFO    Thread-11 :28768 [sender.py:transition_state():602] send defer: 11
