2023-07-10 21:05:17,445 INFO    StreamThr :41143 [internal.py:wandb_internal():86] W&B internal server running at pid: 41143, started at: 2023-07-10 21:05:17.445272
2023-07-10 21:05:17,451 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status
2023-07-10 21:05:17,452 INFO    WriterThread:41143 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/run-0foax46o.wandb
2023-07-10 21:05:17,452 DEBUG   SenderThread:41143 [sender.py:send():369] send: header
2023-07-10 21:05:17,453 DEBUG   SenderThread:41143 [sender.py:send():369] send: run
2023-07-10 21:05:18,388 INFO    SenderThread:41143 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/files
2023-07-10 21:05:18,388 INFO    SenderThread:41143 [sender.py:_start_run_threads():1100] run started: 0foax46o with start time 1688994317.444514
2023-07-10 21:05:18,388 DEBUG   SenderThread:41143 [sender.py:send_request():396] send_request: summary_record
2023-07-10 21:05:18,388 INFO    SenderThread:41143 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 21:05:18,392 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 21:05:18,393 DEBUG   SenderThread:41143 [sender.py:send_request():396] send_request: check_version
2023-07-10 21:05:18,604 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 21:05:18,616 DEBUG   HandlerThread:41143 [system_info.py:__init__():31] System info init
2023-07-10 21:05:18,616 DEBUG   HandlerThread:41143 [system_info.py:__init__():46] System info init done
2023-07-10 21:05:18,616 INFO    HandlerThread:41143 [system_monitor.py:start():181] Starting system monitor
2023-07-10 21:05:18,617 INFO    HandlerThread:41143 [system_monitor.py:probe():201] Collecting system info
2023-07-10 21:05:18,618 INFO    SystemMonitor:41143 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 21:05:18,621 INFO    SystemMonitor:41143 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 21:05:18,625 INFO    SystemMonitor:41143 [interfaces.py:start():190] Started disk monitoring
2023-07-10 21:05:18,628 INFO    SystemMonitor:41143 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 21:05:18,629 INFO    SystemMonitor:41143 [interfaces.py:start():190] Started memory monitoring
2023-07-10 21:05:18,631 INFO    SystemMonitor:41143 [interfaces.py:start():190] Started network monitoring
2023-07-10 21:05:18,641 DEBUG   HandlerThread:41143 [system_info.py:probe():195] Probing system
2023-07-10 21:05:18,645 DEBUG   HandlerThread:41143 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 21:05:18,646 DEBUG   HandlerThread:41143 [system_info.py:probe():240] Probing system done
2023-07-10 21:05:18,646 DEBUG   HandlerThread:41143 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T13:05:18.641888', 'startedAt': '2023-07-10T13:05:17.431043', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 1839.2255416666667, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 1525.456, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1237.908, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1256.312, 'min': 800.0, 'max': 5100.0}, {'current': 1373.495, 'min': 800.0, 'max': 5100.0}, {'current': 1463.884, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1448.911, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 1546.348, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 1301.405, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1411.431, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 967.98, 'min': 800.0, 'max': 4100.0}, {'current': 832.966, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.018589019775390625}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-10 21:05:18,646 INFO    HandlerThread:41143 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 21:05:18,646 INFO    HandlerThread:41143 [system_monitor.py:probe():214] Publishing system info
2023-07-10 21:05:18,646 DEBUG   HandlerThread:41143 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 21:05:18,646 DEBUG   HandlerThread:41143 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 21:05:18,646 DEBUG   HandlerThread:41143 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 21:05:19,390 INFO    Thread-17 :41143 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/files/conda-environment.yaml
2023-07-10 21:05:19,391 INFO    Thread-17 :41143 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/files/requirements.txt
2023-07-10 21:05:19,391 INFO    Thread-17 :41143 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/files/wandb-summary.json
2023-07-10 21:05:19,514 DEBUG   HandlerThread:41143 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 21:05:19,516 INFO    HandlerThread:41143 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 21:05:19,518 DEBUG   SenderThread:41143 [sender.py:send():369] send: files
2023-07-10 21:05:19,519 INFO    SenderThread:41143 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 21:05:19,525 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:05:19,525 DEBUG   SenderThread:41143 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:05:19,998 ERROR   wandb-upload_0:41143 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/0foax46o/wandb-metadata.json?Expires=1689080719&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YFmtaYhGhVVIaF%2FyJ9g9%2BvzekCfrEfCZN5TezaGi1dkYBwx0hD9jzBXEGO8kNuwCfjqzumjFNWJzb57WxabcMB6lbLUZm9lPu%2FVga8Emc05hH35JSXNKNq9rFT85g1wucBvCRw2bf73LjCdQr9%2FAjhCNwY3FiAyMaQR2%2FR%2Fi3PwyHSrIp5wgc2%2FpZVyboQxYzlqYxgb0R5ekz68Jqd2vnqpo9qy%2FeG70WQXEYCMfrdFgvNpzYmnDOT52KaRg%2BzjpX8JdcY%2BkabqN9SJSuFpbi6VHLUPMTY8a8F01K2u6Dlpqml4FJQeuqL%2FslcKMTb2ZrNp2%2BSkrSQ8bfcMoB6kgmA%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/0foax46o/wandb-metadata.json?Expires=1689080719&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YFmtaYhGhVVIaF%2FyJ9g9%2BvzekCfrEfCZN5TezaGi1dkYBwx0hD9jzBXEGO8kNuwCfjqzumjFNWJzb57WxabcMB6lbLUZm9lPu%2FVga8Emc05hH35JSXNKNq9rFT85g1wucBvCRw2bf73LjCdQr9%2FAjhCNwY3FiAyMaQR2%2FR%2Fi3PwyHSrIp5wgc2%2FpZVyboQxYzlqYxgb0R5ekz68Jqd2vnqpo9qy%2FeG70WQXEYCMfrdFgvNpzYmnDOT52KaRg%2BzjpX8JdcY%2BkabqN9SJSuFpbi6VHLUPMTY8a8F01K2u6Dlpqml4FJQeuqL%2FslcKMTb2ZrNp2%2BSkrSQ8bfcMoB6kgmA%3D%3D
2023-07-10 21:05:19,998 ERROR   wandb-upload_0:41143 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3625'}
2023-07-10 21:05:19,998 ERROR   wandb-upload_0:41143 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/0foax46o/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 21:05:20,109 DEBUG   SenderThread:41143 [sender.py:send():369] send: telemetry
2023-07-10 21:05:20,390 INFO    Thread-17 :41143 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/files/conda-environment.yaml
2023-07-10 21:05:20,391 INFO    Thread-17 :41143 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/files/output.log
2023-07-10 21:05:20,391 INFO    Thread-17 :41143 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/files/wandb-metadata.json
2023-07-10 21:05:22,003 ERROR   wandb-upload_0:41143 [upload_job.py:push():136] Failed to upload file: /tmp/tmphac4f9eywandb/gch7gurq-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/0foax46o/wandb-metadata.json?Expires=1689080719&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YFmtaYhGhVVIaF%2FyJ9g9%2BvzekCfrEfCZN5TezaGi1dkYBwx0hD9jzBXEGO8kNuwCfjqzumjFNWJzb57WxabcMB6lbLUZm9lPu%2FVga8Emc05hH35JSXNKNq9rFT85g1wucBvCRw2bf73LjCdQr9%2FAjhCNwY3FiAyMaQR2%2FR%2Fi3PwyHSrIp5wgc2%2FpZVyboQxYzlqYxgb0R5ekz68Jqd2vnqpo9qy%2FeG70WQXEYCMfrdFgvNpzYmnDOT52KaRg%2BzjpX8JdcY%2BkabqN9SJSuFpbi6VHLUPMTY8a8F01K2u6Dlpqml4FJQeuqL%2FslcKMTb2ZrNp2%2BSkrSQ8bfcMoB6kgmA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 21:05:22,391 INFO    Thread-17 :41143 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/files/output.log
2023-07-10 21:05:22,786 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:05:24,010 ERROR   Thread-16 :41143 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmphac4f9eywandb/gch7gurq-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/0foax46o/wandb-metadata.json?Expires=1689080719&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YFmtaYhGhVVIaF%2FyJ9g9%2BvzekCfrEfCZN5TezaGi1dkYBwx0hD9jzBXEGO8kNuwCfjqzumjFNWJzb57WxabcMB6lbLUZm9lPu%2FVga8Emc05hH35JSXNKNq9rFT85g1wucBvCRw2bf73LjCdQr9%2FAjhCNwY3FiAyMaQR2%2FR%2Fi3PwyHSrIp5wgc2%2FpZVyboQxYzlqYxgb0R5ekz68Jqd2vnqpo9qy%2FeG70WQXEYCMfrdFgvNpzYmnDOT52KaRg%2BzjpX8JdcY%2BkabqN9SJSuFpbi6VHLUPMTY8a8F01K2u6Dlpqml4FJQeuqL%2FslcKMTb2ZrNp2%2BSkrSQ8bfcMoB6kgmA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 21:05:24,392 INFO    Thread-17 :41143 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/files/output.log
2023-07-10 21:05:28,001 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:05:30,093 DEBUG   SenderThread:41143 [sender.py:send():369] send: telemetry
2023-07-10 21:05:30,394 INFO    Thread-17 :41143 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/files/output.log
2023-07-10 21:05:32,394 INFO    Thread-17 :41143 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/files/output.log
2023-07-10 21:05:33,160 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:05:34,525 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:05:34,525 DEBUG   SenderThread:41143 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:05:36,289 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 21:05:36,396 INFO    Thread-17 :41143 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/files/output.log
2023-07-10 21:05:38,398 INFO    Thread-17 :41143 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/files/output.log
2023-07-10 21:05:38,458 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:05:43,460 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:05:48,467 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:05:49,407 INFO    Thread-17 :41143 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210517-0foax46o/files/config.yaml
2023-07-10 21:05:49,528 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:05:49,530 DEBUG   SenderThread:41143 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:05:53,763 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:05:58,765 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:06:03,766 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:06:04,526 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:06:04,528 DEBUG   SenderThread:41143 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:06:09,763 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:06:14,764 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:06:18,632 DEBUG   SystemMonitor:41143 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-10 21:06:18,637 DEBUG   SenderThread:41143 [sender.py:send():369] send: stats
2023-07-10 21:06:19,527 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:06:19,529 DEBUG   SenderThread:41143 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:06:20,761 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:06:25,763 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:06:30,764 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:06:34,527 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:06:34,529 DEBUG   SenderThread:41143 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:06:35,770 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:06:40,772 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:06:45,773 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:06:48,640 DEBUG   SenderThread:41143 [sender.py:send():369] send: stats
2023-07-10 21:06:49,527 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:06:49,529 DEBUG   SenderThread:41143 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:06:51,760 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:06:56,761 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:07:01,763 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:07:04,528 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:07:04,530 DEBUG   SenderThread:41143 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:07:06,786 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:07:11,787 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:07:16,789 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:07:18,645 DEBUG   SenderThread:41143 [sender.py:send():369] send: stats
2023-07-10 21:07:19,528 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:07:19,530 DEBUG   SenderThread:41143 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:07:22,785 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:07:27,786 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:07:32,788 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:07:34,528 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:07:34,530 DEBUG   SenderThread:41143 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:07:38,777 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:07:43,779 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:07:48,647 DEBUG   SenderThread:41143 [sender.py:send():369] send: stats
2023-07-10 21:07:49,528 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:07:49,530 DEBUG   SenderThread:41143 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:07:49,772 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:07:54,773 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:07:59,775 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:08:04,528 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:08:04,528 DEBUG   SenderThread:41143 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:08:05,763 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:08:10,765 DEBUG   HandlerThread:41143 [handler.py:handle_request():144] handle_request: status_report
